import type { ThemeMode } from '../types/theme';
import { getSystemTheme } from './systemPreference';
import { lightTheme, darkTheme } from '../themes';

/**
 * Resolve theme mode to actual light or dark value.
 *
 * Converts 'system' mode to the actual OS preference ('light' or 'dark').
 * Direct modes ('light', 'dark') are returned as-is.
 *
 * @param mode - Theme mode to resolve
 * @returns Resolved mode ('light' or 'dark')
 *
 * @example
 * ```tsx
 * const resolved = resolveThemeMode('system');
 * // Returns 'dark' if OS is in dark mode, 'light' otherwise
 * ```
 */
export function resolveThemeMode(mode: ThemeMode): 'light' | 'dark' {
  if (mode === 'system') {
    return getSystemTheme();
  }
  return mode;
}

/**
 * Get vanilla-extract theme class name for resolved mode.
 *
 * @param resolvedMode - Resolved theme mode ('light' or 'dark')
 * @returns CSS class name from vanilla-extract theme
 *
 * @example
 * ```tsx
 * const className = getThemeClassName('dark');
 * // Returns the dark theme class name generated by vanilla-extract
 * ```
 */
export function getThemeClassName(resolvedMode: 'light' | 'dark'): string {
  return resolvedMode === 'dark' ? darkTheme : lightTheme;
}
