# Generated by Django 5.1.4 on 2025-11-27 21:01

from django.contrib.postgres.indexes import GinIndex
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        # Partial indexes for FeatureFlag
        migrations.AddIndex(
            model_name="featureflag",
            index=models.Index(
                fields=["organisation"],
                condition=models.Q(organisation__isnull=False),
                name="flag_org_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="featureflag",
            index=models.Index(
                fields=["project"],
                condition=models.Q(project__isnull=False),
                name="flag_project_idx",
            ),
        ),
        # Partial indexes for Setting
        migrations.AddIndex(
            model_name="setting",
            index=models.Index(
                fields=["organisation"],
                condition=models.Q(organisation__isnull=False),
                name="setting_org_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="setting",
            index=models.Index(
                fields=["project"],
                condition=models.Q(project__isnull=False),
                name="setting_project_idx",
            ),
        ),
        # GIN index for JSONB value field
        migrations.AddIndex(
            model_name="setting",
            index=GinIndex(fields=["value"], name="setting_value_gin_idx"),
        ),
    ]
