# Generated by Django 5.1.4 on 2025-11-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0002_add_indexes"),
    ]

    operations = [
        # Check constraint for FeatureFlag scope consistency
        migrations.AddConstraint(
            model_name="featureflag",
            constraint=models.CheckConstraint(
                check=(
                    (
                        models.Q(scope_type="GLOBAL")
                        & models.Q(organisation__isnull=True)
                        & models.Q(project__isnull=True)
                    )
                    | (
                        models.Q(scope_type="ORGANISATION")
                        & models.Q(organisation__isnull=False)
                        & models.Q(project__isnull=True)
                    )
                    | (
                        models.Q(scope_type="PROJECT")
                        & models.Q(organisation__isnull=False)
                        & models.Q(project__isnull=False)
                    )
                ),
                name="flag_scope_consistency",
            ),
        ),
        # Check constraint for Setting scope consistency
        migrations.AddConstraint(
            model_name="setting",
            constraint=models.CheckConstraint(
                check=(
                    (
                        models.Q(scope_type="GLOBAL")
                        & models.Q(organisation__isnull=True)
                        & models.Q(project__isnull=True)
                    )
                    | (
                        models.Q(scope_type="ORGANISATION")
                        & models.Q(organisation__isnull=False)
                        & models.Q(project__isnull=True)
                    )
                    | (
                        models.Q(scope_type="PROJECT")
                        & models.Q(organisation__isnull=False)
                        & models.Q(project__isnull=False)
                    )
                ),
                name="setting_scope_consistency",
            ),
        ),
    ]
