# Generated by Django 5.1.4 on 2025-11-28 08:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0003_add_check_constraints"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="featureflag",
            name="flag_scope_consistency",
        ),
        migrations.RemoveConstraint(
            model_name="setting",
            name="setting_scope_consistency",
        ),
        migrations.RemoveIndex(
            model_name="featureflag",
            name="flag_org_idx",
        ),
        migrations.RemoveIndex(
            model_name="featureflag",
            name="flag_project_idx",
        ),
        migrations.RemoveIndex(
            model_name="setting",
            name="setting_org_idx",
        ),
        migrations.RemoveIndex(
            model_name="setting",
            name="setting_project_idx",
        ),
        migrations.RemoveIndex(
            model_name="setting",
            name="setting_value_gin_idx",
        ),
    ]
