# Generated by Django 5.1.4 on 2025-11-29
"""
Migration to add USER scope support to settings and feature flags.

This migration:
1. Adds ScopeType.USER enum value
2. Adds user ForeignKey field to Setting model
3. Updates unique constraint to include user field
4. Adds composite indexes for efficient user-scoped queries
"""

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0004_remove_featureflag_flag_scope_consistency_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Update ScopeType choices to include USER for both models
        migrations.AlterField(
            model_name="setting",
            name="scope_type",
            field=models.CharField(
                max_length=20,
                choices=[
                    ("GLOBAL", "Global"),
                    ("ORGANISATION", "Organisation"),
                    ("PROJECT", "Project"),
                    ("USER", "User"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="featureflag",
            name="scope_type",
            field=models.CharField(
                max_length=20,
                choices=[
                    ("GLOBAL", "Global"),
                    ("ORGANISATION", "Organisation"),
                    ("PROJECT", "Project"),
                    ("USER", "User"),
                ],
            ),
        ),
        # Add user field to Setting model
        migrations.AddField(
            model_name="setting",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User for USER-scoped settings (null for other scopes)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # Add user field to FeatureFlag model
        migrations.AddField(
            model_name="featureflag",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User for USER-scoped flags (null for other scopes)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_flags",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # Remove old unique constraints
        migrations.RemoveConstraint(
            model_name="setting",
            name="unique_setting_scope",
        ),
        migrations.RemoveConstraint(
            model_name="featureflag",
            name="unique_flag_scope",
        ),
        # Add new unique constraints that include user
        migrations.AddConstraint(
            model_name="setting",
            constraint=models.UniqueConstraint(
                fields=["key", "scope_type", "user", "organisation", "project"],
                name="unique_setting_scope_with_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="featureflag",
            constraint=models.UniqueConstraint(
                fields=["key", "scope_type", "user", "organisation", "project"],
                name="unique_flag_scope_with_user",
            ),
        ),
        # Add composite indexes for user-scoped queries
        migrations.AddIndex(
            model_name="setting",
            index=models.Index(
                fields=["key", "scope_type", "user"],
                name="idx_setting_user_key",
            ),
        ),
        migrations.AddIndex(
            model_name="setting",
            index=models.Index(
                fields=["user", "key"],
                name="idx_setting_user_lookup",
            ),
        ),
        migrations.AddIndex(
            model_name="featureflag",
            index=models.Index(
                fields=["key", "scope_type", "user"],
                name="idx_flag_user_key",
            ),
        ),
        migrations.AddIndex(
            model_name="featureflag",
            index=models.Index(
                fields=["user", "key"],
                name="idx_flag_user_lookup",
            ),
        ),
    ]
