# Generated by Django 5.1.4 on 2025-12-01 19:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Unique slug (e.g., 'password_reset', 'default')", unique=True
                    ),
                ),
                ("name", models.CharField(help_text="Human-readable name", max_length=100)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Purpose/usage documentation", null=True
                    ),
                ),
                (
                    "default_channel",
                    models.CharField(
                        choices=[("email", "Email"), ("in_app", "In-App"), ("webhook", "Webhook")],
                        help_text="Default channel if not specified",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Soft delete / disable type"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Notification Type",
                "verbose_name_plural": "Notification Types",
                "db_table": "notifications_notification_type",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="RetryPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Policy name (e.g., 'best-effort', 'critical')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Maximum number of delivery attempts",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "retry_window_seconds",
                    models.PositiveIntegerField(
                        default=3600, help_text="Time window for all retries (seconds)"
                    ),
                ),
                (
                    "backoff_strategy",
                    models.CharField(
                        choices=[("linear", "Linear"), ("exponential", "Exponential")],
                        default="exponential",
                        help_text="Backoff strategy for retry delays",
                        max_length=20,
                    ),
                ),
                (
                    "backoff_multiplier",
                    models.FloatField(
                        default=5.0,
                        help_text="Multiplier for exponential backoff (must be > 1.0)",
                        validators=[django.core.validators.MinValueValidator(1.0)],
                    ),
                ),
                (
                    "initial_delay_seconds",
                    models.PositiveIntegerField(
                        default=60, help_text="Delay before first retry (seconds)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Retry Policy",
                "verbose_name_plural": "Retry Policies",
                "db_table": "notifications_retry_policy",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("in_app", "In-App"), ("webhook", "Webhook")],
                        help_text="Delivery channel",
                        max_length=20,
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        help_text="Email address, user ID, or webhook URL", max_length=255
                    ),
                ),
                (
                    "payload",
                    models.JSONField(help_text="Channel-specific data (subject/body/data)"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Optional custom metadata for filtering"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("sent", "Sent"), ("failed", "Failed")],
                        db_index=True,
                        default="pending",
                        help_text="Notification status",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="When notification was created"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="Last status change")),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, help_text="When user read (in-app only)", null=True
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to User model (for in-app)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        help_text="Notification category",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="notifications.notificationtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications_notification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="notificationtype",
            name="retry_policy",
            field=models.ForeignKey(
                help_text="Retry configuration for this type",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notification_types",
                to="notifications.retrypolicy",
            ),
        ),
        migrations.CreateModel(
            name="DeliveryAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(help_text="Attempt sequence (1, 2, 3...)"),
                ),
                (
                    "attempted_at",
                    models.DateTimeField(auto_now_add=True, help_text="When attempt was made"),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("transient_failure", "Transient Failure"),
                            ("permanent_failure", "Permanent Failure"),
                        ],
                        help_text="Delivery outcome",
                        max_length=30,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error details if failed", null=True),
                ),
                (
                    "http_status_code",
                    models.PositiveIntegerField(
                        blank=True, help_text="HTTP status for webhooks", null=True
                    ),
                ),
                (
                    "smtp_response_code",
                    models.PositiveIntegerField(
                        blank=True, help_text="SMTP code for emails", null=True
                    ),
                ),
                (
                    "response_body_snippet",
                    models.TextField(
                        blank=True, help_text="Response body (truncated to 1KB)", null=True
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        blank=True, help_text="Delivery duration in milliseconds", null=True
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        help_text="Parent notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_attempts",
                        to="notifications.notification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery Attempt",
                "verbose_name_plural": "Delivery Attempts",
                "db_table": "notifications_delivery_attempt",
                "ordering": ["notification", "attempt_number"],
                "indexes": [
                    models.Index(
                        fields=["notification", "attempt_number"], name="idx_notification_attempt"
                    ),
                    models.Index(fields=["outcome", "attempted_at"], name="idx_outcome_attempted"),
                ],
                "unique_together": {("notification", "attempt_number")},
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["status", "created_at"], name="idx_status_created"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient_user", "status", "created_at"], name="idx_recipient_user"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["type", "channel", "created_at"], name="idx_type_channel"),
        ),
        migrations.AddIndex(
            model_name="notificationtype",
            index=models.Index(fields=["is_active", "code"], name="idx_type_active"),
        ),
    ]
