# Generated by Django 5.1 on 2025-12-01 20:30

from django.db import migrations


def seed_baseline_data(apps, schema_editor):  # type: ignore[no-untyped-def]
    """Seed baseline notification configuration.

    Creates:
    - "best-effort" RetryPolicy with exponential backoff
    - "default" NotificationType using best-effort policy
    """
    del schema_editor  # Unused but required by Django API
    RetryPolicy = apps.get_model("notifications", "RetryPolicy")
    NotificationType = apps.get_model("notifications", "NotificationType")

    # Create best-effort retry policy
    retry_policy = RetryPolicy.objects.create(
        name="best-effort",
        max_attempts=3,
        retry_window_seconds=3600,
        backoff_strategy="exponential",
        backoff_multiplier=5.0,
        initial_delay_seconds=60,
    )

    # Create default notification type
    NotificationType.objects.create(
        code="default",
        name="Default Notification",
        description="General purpose notification",
        default_channel="email",
        retry_policy=retry_policy,
        is_active=True,
    )


def reverse_seed(apps, schema_editor):  # type: ignore[no-untyped-def]
    """Remove seeded data on migration rollback."""
    del schema_editor  # Unused but required by Django API
    NotificationType = apps.get_model("notifications", "NotificationType")
    RetryPolicy = apps.get_model("notifications", "RetryPolicy")

    # Delete in reverse order due to FK constraint
    NotificationType.objects.filter(code="default").delete()
    RetryPolicy.objects.filter(name="best-effort").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_baseline_data, reverse_seed),
    ]
