# Generated by Django 5.1.4 on 2025-12-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_seed_baseline_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="payload",
            field=models.JSONField(
                blank=True, help_text="Channel-specific data (subject/body/data)"
            ),
        ),
    ]
