# Generated by Django 5.1.4 on 2025-12-01 20:51

from django.db import migrations


def create_critical_retry_policy(apps, schema_editor):
    """Create example 'critical' retry policy for high-priority notifications.

    This policy is designed for critical notifications that need aggressive
    retry behavior:
    - 10 attempts over 24 hours
    - Exponential backoff starting at 5 minutes
    - 2x multiplier for exponential growth
    """
    RetryPolicy = apps.get_model("notifications", "RetryPolicy")

    RetryPolicy.objects.get_or_create(
        name="critical",
        defaults={
            "max_attempts": 10,
            "retry_window_seconds": 86400,  # 24 hours
            "backoff_strategy": "exponential",
            "backoff_multiplier": 2.0,
            "initial_delay_seconds": 300,  # 5 minutes
        },
    )


def remove_critical_retry_policy(apps, schema_editor):
    """Remove critical retry policy."""
    RetryPolicy = apps.get_model("notifications", "RetryPolicy")
    RetryPolicy.objects.filter(name="critical").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_allow_empty_payload"),
    ]

    operations = [
        migrations.RunPython(
            create_critical_retry_policy,
            reverse_code=remove_critical_retry_policy,
        ),
    ]
