# Generated by Django 5.1.4 on 2026-03-19 17:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("organisations", "0004_add_sport_to_organisation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrashItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("object_id", models.UUIDField(help_text="PK of the trashed object")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the object was soft-deleted",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True, help_text="When this item is eligible for permanent deletion"
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        help_text="Human-readable representation of the trashed object (cached at deletion time)",
                        max_length=255,
                    ),
                ),
                (
                    "original_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of key fields at deletion time (for preview without DB lookup)",
                    ),
                ),
                (
                    "restore_path",
                    models.CharField(
                        blank=True,
                        help_text="API path hint for restoring the object",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Type of the trashed object",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trash_items",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trash_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        help_text="Organisation that owns the trashed object",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trash_items",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trash Item",
                "verbose_name_plural": "Trash Items",
                "db_table": "trash_items",
                "ordering": ["-deleted_at"],
                "indexes": [
                    models.Index(fields=["organisation", "-deleted_at"], name="trash_org_deleted"),
                    models.Index(fields=["expires_at"], name="trash_expires"),
                    models.Index(fields=["content_type", "organisation"], name="trash_ct_org"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "object_id"), name="unique_trash_per_object"
                    )
                ],
            },
        ),
    ]
