import { createThemeContract } from '@vanilla-extract/css';

export const colorVars = createThemeContract({
  text: {
    primary: '',
    secondary: '',
    tertiary: '',
    disabled: '',
    inverse: '',
    link: '',
    error: '',
    success: '',
    warning: '',
  },
  background: {
    primary: '',
    secondary: '',
    tertiary: '',
    inverse: '',
    overlay: '',
    success: '',
    warning: '',
    error: '',
    info: '',
  },
  border: {
    primary: '',
    secondary: '',
    focus: '',
    error: '',
  },
  interactive: {
    primary: '',
    primaryHover: '',
    primaryActive: '',
    secondary: '',
    secondaryHover: '',
    secondaryActive: '',
    destructive: '',
    destructiveHover: '',
    destructiveActive: '',
    disabled: '',
  },
  palette: {
    neutral: {
      '50': '',
      '100': '',
      '200': '',
      '300': '',
      '400': '',
      '500': '',
      '600': '',
      '700': '',
      '800': '',
      '900': '',
      '950': '',
    },
    primary: {
      '50': '',
      '100': '',
      '200': '',
      '300': '',
      '400': '',
      '500': '',
      '600': '',
      '700': '',
      '800': '',
      '900': '',
      '950': '',
    },
    success: {
      '50': '',
      '100': '',
      '200': '',
      '300': '',
      '400': '',
      '500': '',
      '600': '',
      '700': '',
      '800': '',
      '900': '',
      '950': '',
    },
    warning: {
      '50': '',
      '100': '',
      '200': '',
      '300': '',
      '400': '',
      '500': '',
      '600': '',
      '700': '',
      '800': '',
      '900': '',
      '950': '',
    },
    error: {
      '50': '',
      '100': '',
      '200': '',
      '300': '',
      '400': '',
      '500': '',
      '600': '',
      '700': '',
      '800': '',
      '900': '',
      '950': '',
    },
  },
});
