# Generated by Django 5.1.4 on 2026-01-30 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0014_restore_unique_active_project_membership"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable sport name (e.g., 'Football 11v11')",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier (e.g., 'football-11')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "federation_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Federation info, e.g., {'code': 'KNVB', 'country': 'NL'}",
                    ),
                ),
                (
                    "sport_icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon identifier or emoji, e.g., '⚽' or 'football'",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this sport is available for selection",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sport",
                "verbose_name_plural": "Sports",
                "db_table": "sport_configuration_sport",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SportConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "team_size_min",
                    models.PositiveIntegerField(
                        default=1, help_text="Minimum players in starting lineup"
                    ),
                ),
                (
                    "team_size_max",
                    models.PositiveIntegerField(
                        default=11, help_text="Maximum players in starting lineup"
                    ),
                ),
                (
                    "max_substitutes",
                    models.PositiveIntegerField(default=7, help_text="Maximum substitute players"),
                ),
                (
                    "positions",
                    models.JSONField(
                        default=list,
                        help_text="Standard positions, e.g., ['GK', 'LB', 'CB', 'RB', 'CM', 'ST']",
                    ),
                ),
                (
                    "formations",
                    models.JSONField(
                        default=dict,
                        help_text="Formation templates, e.g., {'4-3-3': {'positions': [...], 'name': '4-3-3'}}",
                    ),
                ),
                (
                    "outfit_types",
                    models.JSONField(
                        default=list,
                        help_text="Required outfit types, e.g., ['home', 'away', 'goalkeeper', 'trainer']",
                    ),
                ),
                (
                    "has_goalkeeper",
                    models.BooleanField(
                        default=True, help_text="Whether this sport has a designated goalkeeper"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional sport-specific rules"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sport",
                    models.OneToOneField(
                        help_text="Sport this configuration applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuration",
                        to="sport_configuration.sport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sport Configuration",
                "verbose_name_plural": "Sport Configurations",
                "db_table": "sport_configuration_sportconfiguration",
            },
        ),
        migrations.CreateModel(
            name="OutfitConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "outfit_type",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("away", "Away"),
                            ("goalkeeper", "Goalkeeper"),
                            ("trainer", "Trainer"),
                            ("third_kit", "Third Kit"),
                        ],
                        help_text="Type of outfit (home, away, goalkeeper, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "colors",
                    models.JSONField(
                        default=dict,
                        help_text="Color scheme: {'primary': '#FF0000', 'secondary': '#FFFFFF', 'accent': '#000000'}",
                    ),
                ),
                (
                    "sponsor_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Sponsor positioning: {'chest': 'Sponsor A', 'sleeve': 'Sponsor B'}",
                    ),
                ),
                (
                    "number_font",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Number styling: {'family': 'Arial', 'color': '#FFFFFF', 'outline': '#000000'}",
                    ),
                ),
                (
                    "badge_position",
                    models.CharField(
                        default="left_chest",
                        help_text="Badge placement: left_chest, center_chest, etc.",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional outfit metadata"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this outfit configuration is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project (club or team) this outfit belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outfit_configurations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outfit Configuration",
                "verbose_name_plural": "Outfit Configurations",
                "db_table": "sport_configuration_outfitconfiguration",
                "ordering": ["project", "outfit_type"],
                "unique_together": {("project", "outfit_type")},
            },
        ),
    ]
