# Generated by Django 5.1.4 on 2026-01-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sport_configuration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outfitconfiguration",
            name="colors",
            field=models.JSONField(
                default=dict,
                help_text="Color scheme: {'primary': '#FF0000', 'secondary': '#FFFFFF'}",
            ),
        ),
    ]
