# Generated by Django 5.1.4 on 2026-01-30 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sport_configuration", "0002_add_sport_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="sport",
            name="parent_sport",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent sport category. NULL = this is a category, SET = this is a variant",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="sport_configuration.sport",
            ),
        ),
        migrations.AddField(
            model_name="sportconfiguration",
            name="has_corner_kicks",
            field=models.BooleanField(
                default=True, help_text="Whether this variant has corner kicks (False for futsal)"
            ),
        ),
        migrations.AddField(
            model_name="sportconfiguration",
            name="has_offside",
            field=models.BooleanField(
                default=True, help_text="Whether offside rule applies (False for some variants)"
            ),
        ),
        migrations.AddField(
            model_name="sportconfiguration",
            name="match_duration_minutes",
            field=models.PositiveIntegerField(
                default=90, help_text="Standard match duration in minutes"
            ),
        ),
        migrations.AddField(
            model_name="sportconfiguration",
            name="pitch_type",
            field=models.CharField(
                default="outdoor_large",
                help_text="Pitch type: outdoor_large, outdoor_small, indoor, court",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="sport",
            name="name",
            field=models.CharField(
                help_text="Human-readable sport name (e.g., 'Football' or 'Football 11v11')",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="sport",
            name="slug",
            field=models.SlugField(
                help_text="URL-safe identifier (e.g., 'football' or 'football-11v11')",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="sportconfiguration",
            name="sport",
            field=models.OneToOneField(
                help_text="Sport (variant) this configuration applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configuration",
                to="sport_configuration.sport",
            ),
        ),
        migrations.AddIndex(
            model_name="sport",
            index=models.Index(fields=["parent_sport"], name="idx_sport_parent"),
        ),
    ]
