# Generated by Django 5.1.4 on 2026-01-30

from __future__ import annotations

from typing import Any

from django.db import migrations


SPORT_CATEGORIES: list[dict[str, Any]] = [
    {"name": "Football", "slug": "football", "sport_icon": "⚽"},
    {"name": "Handball", "slug": "handball", "sport_icon": "🤾"},
    {"name": "Basketball", "slug": "basketball", "sport_icon": "🏀"},
    {"name": "Volleyball", "slug": "volleyball", "sport_icon": "🏐"},
    {"name": "Rugby", "slug": "rugby", "sport_icon": "🏉"},
    {"name": "Hockey", "slug": "hockey", "sport_icon": "🏒"},
]


SPORTS_DATA: list[dict[str, Any]] = [
    {
        "name": "Football 11v11",
        "slug": "football-11v11",
        "sport_icon": "⚽",
        "parent_slug": "football",
        "config": {
            "team_size_min": 11,
            "team_size_max": 11,
            "max_substitutes": 7,
            "pitch_type": "outdoor_large",
            "has_corner_kicks": True,
            "has_offside": True,
            "match_duration_minutes": 90,
            "positions": [
                "GK",
                "LB",
                "CB",
                "RB",
                "LWB",
                "RWB",
                "DM",
                "CM",
                "AM",
                "LM",
                "RM",
                "LW",
                "RW",
                "CF",
                "ST",
            ],
            "formations": {
                "4-3-3": {
                    "description": "Standard attacking formation",
                    "positions": ["GK", "LB", "CB", "CB", "RB", "CM", "CM", "CM", "LW", "ST", "RW"],
                },
                "4-4-2": {
                    "description": "Classic balanced formation",
                    "positions": ["GK", "LB", "CB", "CB", "RB", "LM", "CM", "CM", "RM", "ST", "ST"],
                },
                "3-5-2": {
                    "description": "Wingback formation",
                    "positions": [
                        "GK",
                        "CB",
                        "CB",
                        "CB",
                        "LWB",
                        "CM",
                        "CM",
                        "CM",
                        "RWB",
                        "ST",
                        "ST",
                    ],
                },
                "4-2-3-1": {
                    "description": "Modern defensive formation",
                    "positions": ["GK", "LB", "CB", "CB", "RB", "DM", "DM", "LW", "AM", "RW", "ST"],
                },
            },
            "outfit_types": ["home", "away", "goalkeeper", "third_kit"],
            "has_goalkeeper": True,
        },
    },
    {
        "name": "Futsal 5v5",
        "slug": "futsal-5v5",
        "sport_icon": "⚽",
        "parent_slug": "football",
        "config": {
            "team_size_min": 5,
            "team_size_max": 5,
            "max_substitutes": 7,
            "pitch_type": "indoor",
            "has_corner_kicks": False,
            "has_offside": False,
            "match_duration_minutes": 40,
            "positions": ["GK", "FIXO", "ALA", "PIVOT"],
            "formations": {
                "1-2-2": {
                    "description": "Standard defensive setup",
                    "positions": ["GK", "FIXO", "ALA", "ALA", "PIVOT"],
                },
                "2-2": {
                    "description": "Flat formation without dedicated fixo",
                    "positions": ["GK", "ALA", "ALA", "PIVOT", "PIVOT"],
                },
                "1-1-2-1": {
                    "description": "Attacking diamond",
                    "positions": ["GK", "FIXO", "ALA", "ALA", "PIVOT"],
                },
            },
            "outfit_types": ["home", "away", "goalkeeper"],
            "has_goalkeeper": True,
        },
    },
    {
        "name": "Football 7v7",
        "slug": "football-7v7",
        "sport_icon": "⚽",
        "parent_slug": "football",
        "config": {
            "team_size_min": 7,
            "team_size_max": 7,
            "max_substitutes": 5,
            "pitch_type": "outdoor_small",
            "has_corner_kicks": True,
            "has_offside": False,
            "match_duration_minutes": 50,
            "positions": ["GK", "DEF", "MID", "FWD"],
            "formations": {
                "2-3-1": {
                    "description": "Standard youth formation",
                    "positions": ["GK", "DEF", "DEF", "MID", "MID", "MID", "FWD"],
                },
                "3-2-1": {
                    "description": "Defensive formation",
                    "positions": ["GK", "DEF", "DEF", "DEF", "MID", "MID", "FWD"],
                },
            },
            "outfit_types": ["home", "away", "goalkeeper"],
            "has_goalkeeper": True,
        },
    },
    {
        "name": "Indoor Handball",
        "slug": "handball-indoor",
        "sport_icon": "🤾",
        "parent_slug": "handball",
        "config": {
            "team_size_min": 7,
            "team_size_max": 7,
            "max_substitutes": 7,
            "pitch_type": "indoor",
            "has_corner_kicks": False,
            "has_offside": False,
            "match_duration_minutes": 60,
            "positions": ["GK", "LW", "LB", "CB", "RB", "RW", "P"],
            "formations": {
                "6-0": {
                    "description": "Standard defensive formation",
                    "positions": ["GK", "LW", "LB", "CB", "CB", "RB", "RW"],
                },
                "5-1": {
                    "description": "Aggressive defensive formation",
                    "positions": ["GK", "LW", "LB", "CB", "RB", "RW", "P"],
                },
            },
            "outfit_types": ["home", "away", "goalkeeper"],
            "has_goalkeeper": True,
        },
    },
    {
        "name": "Basketball 5v5",
        "slug": "basketball-5v5",
        "sport_icon": "🏀",
        "parent_slug": "basketball",
        "config": {
            "team_size_min": 5,
            "team_size_max": 5,
            "max_substitutes": 7,
            "pitch_type": "court",
            "has_corner_kicks": False,
            "has_offside": False,
            "match_duration_minutes": 48,
            "positions": ["PG", "SG", "SF", "PF", "C"],
            "formations": {},
            "outfit_types": ["home", "away"],
            "has_goalkeeper": False,
        },
    },
    {
        "name": "Indoor Volleyball",
        "slug": "volleyball-indoor",
        "sport_icon": "🏐",
        "parent_slug": "volleyball",
        "config": {
            "team_size_min": 6,
            "team_size_max": 6,
            "max_substitutes": 6,
            "pitch_type": "court",
            "has_corner_kicks": False,
            "has_offside": False,
            "match_duration_minutes": 90,
            "positions": ["SETTER", "LIBERO", "OPPOSITE", "OUTSIDE", "MIDDLE"],
            "formations": {
                "5-1": {
                    "description": "One setter rotation",
                    "positions": ["SETTER", "OUTSIDE", "OUTSIDE", "MIDDLE", "MIDDLE", "OPPOSITE"],
                },
                "6-2": {
                    "description": "Two setter rotation",
                    "positions": ["SETTER", "SETTER", "OUTSIDE", "OUTSIDE", "MIDDLE", "MIDDLE"],
                },
            },
            "outfit_types": ["home", "away", "libero"],
            "has_goalkeeper": False,
        },
    },
    {
        "name": "Rugby Union",
        "slug": "rugby-union",
        "sport_icon": "🏉",
        "parent_slug": "rugby",
        "config": {
            "team_size_min": 15,
            "team_size_max": 15,
            "max_substitutes": 8,
            "pitch_type": "outdoor_large",
            "has_corner_kicks": False,
            "has_offside": True,
            "match_duration_minutes": 80,
            "positions": [
                "PROP",
                "HOOKER",
                "LOCK",
                "FLANKER",
                "NO8",
                "SCRUMHALF",
                "FLYHALF",
                "CENTER",
                "WING",
                "FULLBACK",
            ],
            "formations": {},
            "outfit_types": ["home", "away"],
            "has_goalkeeper": False,
        },
    },
    {
        "name": "Ice Hockey",
        "slug": "ice-hockey",
        "sport_icon": "🏒",
        "parent_slug": "hockey",
        "config": {
            "team_size_min": 6,
            "team_size_max": 6,
            "max_substitutes": 17,
            "pitch_type": "ice_rink",
            "has_corner_kicks": False,
            "has_offside": True,
            "match_duration_minutes": 60,
            "positions": ["GOALIE", "LD", "RD", "LW", "C", "RW"],
            "formations": {},
            "outfit_types": ["home", "away", "goalie"],
            "has_goalkeeper": True,
        },
    },
    {
        "name": "Field Hockey",
        "slug": "field-hockey",
        "sport_icon": "🏑",
        "parent_slug": "hockey",
        "config": {
            "team_size_min": 11,
            "team_size_max": 11,
            "max_substitutes": 5,
            "pitch_type": "outdoor_large",
            "has_corner_kicks": True,
            "has_offside": False,
            "match_duration_minutes": 70,
            "positions": ["GK", "DEF", "MID", "FWD"],
            "formations": {
                "3-3-3-1": {
                    "description": "Standard formation",
                    "positions": [
                        "GK",
                        "DEF",
                        "DEF",
                        "DEF",
                        "MID",
                        "MID",
                        "MID",
                        "FWD",
                        "FWD",
                        "FWD",
                        "FWD",
                    ],
                },
            },
            "outfit_types": ["home", "away", "goalkeeper"],
            "has_goalkeeper": True,
        },
    },
]


def seed_baseline_sports(apps, _schema_editor) -> None:
    Sport = apps.get_model("sport_configuration", "Sport")
    SportConfiguration = apps.get_model("sport_configuration", "SportConfiguration")

    category_map: dict[str, Any] = {}
    for cat in SPORT_CATEGORIES:
        category, _created = Sport.objects.update_or_create(
            slug=cat["slug"],
            defaults={
                "name": cat["name"],
                "sport_icon": cat.get("sport_icon", ""),
                "parent_sport": None,
                "is_active": True,
            },
        )
        category_map[cat["slug"]] = category

    for sport_data in SPORTS_DATA:
        parent = category_map.get(sport_data["parent_slug"])
        if parent is None:
            continue

        sport, _created = Sport.objects.update_or_create(
            slug=sport_data["slug"],
            defaults={
                "name": sport_data["name"],
                "sport_icon": sport_data.get("sport_icon", ""),
                "parent_sport": parent,
                "is_active": True,
            },
        )

        config = sport_data["config"]
        SportConfiguration.objects.update_or_create(
            sport=sport,
            defaults={
                "team_size_min": config["team_size_min"],
                "team_size_max": config["team_size_max"],
                "max_substitutes": config.get("max_substitutes", 7),
                "positions": config.get("positions", []),
                "formations": config.get("formations", {}),
                "outfit_types": config.get("outfit_types", ["home", "away"]),
                "has_goalkeeper": config.get("has_goalkeeper", False),
                "pitch_type": config.get("pitch_type", "outdoor_large"),
                "has_corner_kicks": config.get("has_corner_kicks", True),
                "has_offside": config.get("has_offside", True),
                "match_duration_minutes": config.get("match_duration_minutes", 90),
            },
        )


def noop_reverse(_apps, _schema_editor) -> None:
    # Production-safety: do not delete seeded rows automatically.
    return


class Migration(migrations.Migration):
    dependencies = [
        ("sport_configuration", "0003_add_sport_hierarchy"),
    ]

    operations = [
        migrations.RunPython(seed_baseline_sports, reverse_code=noop_reverse),
    ]
