# Generated by Django 5.1.4 on 2026-01-31 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sport_configuration", "0004_seed_baseline_sports"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Formation code (e.g., '4-3-3', '4-4-2', '3-5-2')", max_length=20
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., '4-3-3 Attacking')", max_length=100
                    ),
                ),
                (
                    "positions",
                    models.JSONField(
                        default=list,
                        help_text="Position slots: [{'slot': 1, 'position': 'GK', 'x': 50, 'y': 90}, ...]",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Formation description and tactical notes"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default formation for this sport",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this formation is available for selection",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in formation picker (lower = first)"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional formation metadata (AI hints, visualization settings)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sport_config",
                    models.ForeignKey(
                        help_text="Sport configuration this formation belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formation_set",
                        to="sport_configuration.sportconfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formation",
                "verbose_name_plural": "Formations",
                "db_table": "sport_configuration_formation",
                "ordering": ["sport_config", "display_order", "code"],
                "indexes": [
                    models.Index(
                        fields=["sport_config", "is_active"], name="idx_formation_sport_active"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sport_config", "code"), name="unique_formation_code_per_sport"
                    )
                ],
            },
        ),
    ]
