[program:celery-worker]
command=/var/www/django-core/venv/bin/celery -A config worker --loglevel=info --concurrency=4
directory=/var/www/django-core/src
user=www-data
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/celery/worker.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
stopwaitsecs=300
stopsignal=TERM

; Environment variables
environment=DJANGO_SETTINGS_MODULE="config.settings.production",CELERY_BROKER_URL="redis://localhost:6379/0",CELERY_RESULT_BACKEND="redis://localhost:6379/0"
