# Generated by Django 5.1.4 on 2026-01-29 20:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("activities", "0006_activity_slug"),
        ("files", "0002_add_thumbnail_path"),
        ("organisations", "0003_add_metadata_fields"),
        ("projects", "0014_restore_unique_active_project_membership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template display name (e.g., 'Line-up Video')", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Template purpose and usage notes", null=True
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("pre_match", "Pre-Match"),
                            ("during_match", "During Match"),
                            ("post_match", "Post-Match"),
                            ("season", "Season Summary"),
                            ("custom", "Custom"),
                        ],
                        db_index=True,
                        help_text="Template category",
                        max_length=50,
                    ),
                ),
                (
                    "sport_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Sport identifier (links to B32, e.g., 'football')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "ai_workflow_id",
                    models.CharField(
                        help_text="External AI system workflow/pipeline identifier", max_length=200
                    ),
                ),
                (
                    "template_settings",
                    models.JSONField(
                        default=dict,
                        help_text="AI-specific configuration (schema varies by workflow)",
                    ),
                ),
                (
                    "timeout_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Generation timeout in minutes (NULL uses system default of 30)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1440),
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Template availability flag"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Template creator",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        help_text="Owning organization",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_templates",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional project scope (NULL = org-wide)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_templates",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Template",
                "verbose_name_plural": "Content Templates",
                "db_table": "content_generation_contenttemplate",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("revision_requested", "Revision Requested"),
                        ],
                        db_index=True,
                        default="queued",
                        help_text="Generation status",
                        max_length=30,
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(default=dict, help_text="User-provided generation inputs"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Failure details (populated when status='failed')",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional tracking data (duration, retries, etc.)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, help_text="Soft-delete timestamp", null=True
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional linked activity (match/event via B30)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_items",
                        to="activities.activity",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Content creator",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_content_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "output_file",
                    models.ForeignKey(
                        blank=True,
                        help_text="Generated file (via B22)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_items",
                        to="files.fileasset",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project scope",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_items",
                        to="projects.project",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="Source template",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contentitem_set",
                        to="content_generation.contenttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Item",
                "verbose_name_plural": "Content Items",
                "db_table": "content_generation_contentitem",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("revision_requested", "Revision Requested"),
                        ],
                        db_index=True,
                        help_text="Approval decision",
                        max_length=30,
                    ),
                ),
                (
                    "feedback_text",
                    models.TextField(blank=True, help_text="Reviewer comments/notes", null=True),
                ),
                ("reviewed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        help_text="Approving/rejecting user",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="content_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_item",
                    models.ForeignKey(
                        help_text="Related content item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contentapproval_set",
                        to="content_generation.contentitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Approval",
                "verbose_name_plural": "Content Approvals",
                "db_table": "content_generation_contentapproval",
                "ordering": ["-reviewed_at"],
                "indexes": [
                    models.Index(fields=["content_item", "reviewed_at"], name="idx_approval_item"),
                    models.Index(fields=["status", "reviewed_at"], name="idx_approval_status"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="contenttemplate",
            index=models.Index(
                fields=["is_active", "sport_type"], name="idx_template_active_sport"
            ),
        ),
        migrations.AddIndex(
            model_name="contenttemplate",
            index=models.Index(
                fields=["organisation", "is_active"], name="idx_template_org_active"
            ),
        ),
        migrations.AddIndex(
            model_name="contenttemplate",
            index=models.Index(fields=["name"], name="idx_template_name"),
        ),
        migrations.AddConstraint(
            model_name="contenttemplate",
            constraint=models.UniqueConstraint(
                fields=("organisation", "name"), name="unique_template_name_per_org"
            ),
        ),
        migrations.AddIndex(
            model_name="contentitem",
            index=models.Index(
                fields=["project", "status", "deleted_at"], name="idx_item_project_status"
            ),
        ),
        migrations.AddIndex(
            model_name="contentitem",
            index=models.Index(
                fields=["template", "activity", "status"], name="idx_item_duplicate"
            ),
        ),
        migrations.AddIndex(
            model_name="contentitem",
            index=models.Index(fields=["status", "created_at"], name="idx_item_status_created"),
        ),
    ]
