# Generated by Django 5.1.4 on 2026-01-30 07:00
"""
B31 Content Templates & Generation - Seed Initial Templates

This migration seeds the database with starter templates for common content types.
Uses get_or_create to be idempotent (safe to run multiple times).
"""

from django.db import migrations


def seed_templates(apps, schema_editor):
    """Seed initial content templates for common use cases."""
    ContentTemplate = apps.get_model("content_generation", "ContentTemplate")
    User = apps.get_model("accounts", "User")
    Organisation = apps.get_model("organisations", "Organisation")

    # Get first user and org for seeding (if they exist)
    user = User.objects.first()
    org = Organisation.objects.first()

    if not user or not org:
        # Skip seeding if no users or orgs exist yet
        return

    templates = [
        {
            "name": "Line-up Video",
            "description": "Generate video showing starting line-up with player names and formation",
            "template_type": "pre_match",
            "sport_type": "football",
            "ai_workflow_id": "workflow_lineup_v2",
            "template_settings": {
                "duration_seconds": 30,
                "background_music": True,
                "show_formation": True,
            },
            "timeout_minutes": 15,
            "is_active": True,
        },
        {
            "name": "Match Highlights",
            "description": "Generate 90-second highlight reel with goals and key moments",
            "template_type": "post_match",
            "sport_type": "football",
            "ai_workflow_id": "workflow_highlights_v3",
            "template_settings": {
                "duration_seconds": 90,
                "include_goals": True,
                "include_cards": True,
            },
            "timeout_minutes": 30,
            "is_active": True,
        },
        {
            "name": "Player Stats Card",
            "description": "Generate social media card with player statistics",
            "template_type": "in_match",
            "sport_type": "football",
            "ai_workflow_id": "workflow_stats_card_v1",
            "template_settings": {
                "card_format": "square",
                "include_photo": True,
            },
            "timeout_minutes": 5,
            "is_active": True,
        },
    ]

    for template_data in templates:
        ContentTemplate.objects.get_or_create(
            name=template_data["name"],
            organisation=org,
            defaults={
                **template_data,
                "organisation": org,
                "created_by": user,
            },
        )


def reverse_seed(apps, schema_editor):
    """Remove seeded templates (for migration rollback)."""
    ContentTemplate = apps.get_model("content_generation", "ContentTemplate")
    ContentTemplate.objects.filter(
        name__in=["Line-up Video", "Match Highlights", "Player Stats Card"]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("content_generation", "0001_initial"),
        ("accounts", "0001_initial"),
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_templates, reverse_seed),
    ]
