# Generated by Django 5.1.4 on 2026-01-30 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_generation", "0002_seed_initial_templates"),
        ("sport_configuration", "0002_add_sport_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="contenttemplate",
            name="sport",
            field=models.ForeignKey(
                blank=True,
                help_text="Filter templates by sport. Null = universal template.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_templates",
                to="sport_configuration.sport",
            ),
        ),
    ]
