# Generated by Django 5.1.4 on 2026-01-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_generation", "0003_add_sport_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="contenttemplate",
            name="template_subtype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("flyer", "Match Flyer"),
                    ("lineup", "Lineup Announcement"),
                    ("walkon", "Walk-on Video"),
                    ("anthem", "Anthem Video"),
                    ("goal", "Goal Celebration"),
                    ("score_update", "Score Update"),
                    ("end_score", "Final Score"),
                    ("match_summary", "Match Summary"),
                    ("highlights", "Highlights Reel"),
                    ("transformation", "Then vs Now"),
                    ("season_recap", "Season Recap"),
                    ("member_intro", "Short Intro"),
                    ("member_closeup", "Closeup Video"),
                    ("member_celebration", "Personal Celebration"),
                ],
                db_index=True,
                help_text="Specific template type (what)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contenttemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("pre_match", "Pre-Match"),
                    ("during_match", "During Match"),
                    ("post_match", "Post-Match"),
                    ("season", "Season"),
                    ("member", "Member"),
                    ("custom", "Custom"),
                ],
                db_index=True,
                help_text="Template category (when)",
                max_length=50,
            ),
        ),
    ]
