# Generated by Django 5.1.4 on 2026-01-31 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_generation", "0004_add_template_subtype"),
        ("sport_configuration", "0005_add_formation_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="contenttemplate",
            name="formation",
            field=models.ForeignKey(
                blank=True,
                help_text="Formation this template is designed for (e.g., 4-3-3). Only for lineup templates.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_templates",
                to="sport_configuration.formation",
            ),
        ),
        migrations.AddField(
            model_name="contenttemplate",
            name="style_variant",
            field=models.CharField(
                blank=True,
                help_text="Visual style variant name (e.g., 'Modern', 'Classic', 'Neon')",
                max_length=100,
                null=True,
            ),
        ),
    ]
