# Generated by Django 5.1.4 on 2026-01-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_generation", "0005_add_formation_and_style_to_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="contenttemplate",
            name="input_requirements",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Input requirements for content generation. Schema:\n        {\n            "players": {\n                "use_formation": true,  // Use positions from linked Formation\n                "min_count": 11,\n                "max_count": 11,\n                "positions": ["GK", "LB", "CB", "CB", "RB", "CM", "CM", "CM", "LW", "ST", "RW"]\n            },\n            "staff": [\n                {"role": "coach", "required": true, "count": 1},\n                {"role": "assistant", "required": false, "count": 1}\n            ],\n            "assets": [\n                {"type": "team_logo", "required": true},\n                {"type": "opponent_logo", "required": false},\n                {"type": "sponsor_logo", "required": false}\n            ],\n            "match_data": {\n                "required": ["date", "opponent", "venue"],\n                "optional": ["kickoff_time", "competition"]\n            }\n        }',
            ),
        ),
    ]
