# Generated by Django 5.1.4 on 2026-01-31 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_generation", "0006_add_input_requirements"),
        ("organisations", "0004_add_sport_to_organisation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="contenttemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Template creator. NULL for system-seeded templates.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contenttemplate",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization. NULL = global template (superadmin only)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_templates",
                to="organisations.organisation",
            ),
        ),
    ]
