# Generated by Django 5.1.4 on 2026-01-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_generation", "0007_make_organisation_and_created_by_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="contenttemplate",
            name="credits_required",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of credits required to generate content with this template",
            ),
        ),
    ]
