# Generated by Django 5.1.4 on 2026-02-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_generation", "0010_update_member_subtypes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contenttemplate",
            name="template_subtype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("flyer", "Match Flyer"),
                    ("lineup", "Lineup Announcement"),
                    ("walkon", "Walk-on Video"),
                    ("anthem", "Anthem Video"),
                    ("goal", "Goal Celebration"),
                    ("score_update", "Score Update"),
                    ("end_score", "Final Score"),
                    ("match_summary", "Match Summary"),
                    ("highlights", "Highlights Reel"),
                    ("transformation", "Then vs Now"),
                    ("season_recap", "Season Recap"),
                    ("profile_photo", "Profile Photo"),
                    ("legacy_photo", "Legacy Photo"),
                    ("closeup", "Close-up"),
                    ("member_intro", "Short Intro"),
                    ("member_goal_celebration", "Goal Celebration"),
                    ("member_in_tenue", "In Tenue"),
                    ("member_legacy_closeup", "Legacy Closeup"),
                    ("member_legacy_in_tenue", "Legacy In Tenue"),
                    ("custom_logo", "Logo"),
                    ("custom_tenue", "Tenue"),
                    ("custom_tenue_logo", "Tenue + Logo"),
                    ("custom_tenue_logo_sponsor", "Tenue + Logo + Sponsor"),
                ],
                db_index=True,
                help_text="Specific template type (what)",
                max_length=50,
                null=True,
            ),
        ),
    ]
