# Generated by Django 5.1.4 on 2026-02-17

from django.db import migrations, models


def seed_lineup_flyer_templates(apps, _schema_editor):
    ContentTemplate = apps.get_model("content_generation", "ContentTemplate")
    Sport = apps.get_model("sport_configuration", "Sport")

    def build_input_requirements(player_count: int) -> dict:
        return {
            "members": {
                "goalkeeper": {
                    "count": 1,
                    "asset_types": ["in_tenue", "closeup"],
                },
                "player": {
                    "count": max(player_count - 1, 0),
                    "asset_types": ["in_tenue", "closeup"],
                },
            },
            "use_formation": True,
            "assets": [
                {"type": "team_logo", "required": True},
                {"type": "background", "required": False},
            ],
            "match_data": {
                "required": ["opponent", "date", "venue"],
                "optional": ["kickoff_time", "competition"],
            },
        }

    variants = [
        (
            "football-11v11",
            "Lineup Flyer - Modern (Football 11v11)",
            11,
            "wf_lineup_flyer_modern_11v11",
        ),
        ("football-7v7", "Lineup Flyer - Modern (Football 7v7)", 7, "wf_lineup_flyer_modern_7v7"),
        ("futsal-5v5", "Lineup Flyer - Modern (Futsal 5v5)", 5, "wf_lineup_flyer_modern_futsal"),
    ]
    for sport_slug, name, player_count, workflow_id in variants:
        sport = Sport.objects.filter(slug=sport_slug).first()
        ContentTemplate.objects.update_or_create(
            organisation=None,
            name=name,
            defaults={
                "description": "Static lineup flyer (PNG) generated from activity + selected members.",
                "template_type": "pre_match",
                "template_subtype": "lineup_flyer",
                "style_variant": "Modern",
                "ai_workflow_id": workflow_id,
                "input_requirements": build_input_requirements(player_count),
                "credits_required": 1,
                "sport": sport,
                "is_active": True,
                "created_by": None,
            },
        )

    # If sport variants don't exist yet, ensure at least one global template exists.
    if not Sport.objects.filter(slug__in=[v[0] for v in variants]).exists():
        ContentTemplate.objects.update_or_create(
            organisation=None,
            name="Lineup Flyer - Modern",
            defaults={
                "description": "Static lineup flyer (PNG) generated from activity + selected members.",
                "template_type": "pre_match",
                "template_subtype": "lineup_flyer",
                "style_variant": "Modern",
                "ai_workflow_id": "wf_lineup_flyer_modern",
                "input_requirements": build_input_requirements(11),
                "credits_required": 1,
                "sport": None,
                "is_active": True,
                "created_by": None,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("content_generation", "0011_alter_contenttemplate_template_subtype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contenttemplate",
            name="template_subtype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("flyer", "Match Flyer"),
                    ("lineup", "Lineup Announcement"),
                    ("lineup_flyer", "Lineup Flyer"),
                    ("walkon", "Walk-on Video"),
                    ("anthem", "Anthem Video"),
                    ("goal", "Goal Celebration"),
                    ("score_update", "Score Update"),
                    ("end_score", "Final Score"),
                    ("match_summary", "Match Summary"),
                    ("highlights", "Highlights Reel"),
                    ("transformation", "Then vs Now"),
                    ("season_recap", "Season Recap"),
                    ("profile_photo", "Profile Photo"),
                    ("legacy_photo", "Legacy Photo"),
                    ("closeup", "Close-up"),
                    ("member_intro", "Short Intro"),
                    ("member_goal_celebration", "Goal Celebration"),
                    ("member_in_tenue", "In Tenue"),
                    ("member_legacy_closeup", "Legacy Closeup"),
                    ("member_legacy_in_tenue", "Legacy In Tenue"),
                    ("custom_logo", "Logo"),
                    ("custom_tenue", "Tenue"),
                    ("custom_tenue_logo", "Tenue + Logo"),
                    ("custom_tenue_logo_sponsor", "Tenue + Logo + Sponsor"),
                ],
                db_index=True,
                help_text="Specific template type (what)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.RunPython(seed_lineup_flyer_templates, reverse_code=migrations.RunPython.noop),
    ]
