# Generated by Django 5.1.4 on 2026-03-19 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_generation", "0013_fix_lineup_flyer_asset_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contentitem",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who soft-deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Timestamp when this record was soft-deleted (NULL = active)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contenttemplate",
            name="template_subtype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("flyer", "Match Flyer"),
                    ("lineup", "Lineup Announcement"),
                    ("lineup_flyer", "Lineup Flyer"),
                    ("walkon", "Walk-on Video"),
                    ("anthem", "Anthem Video"),
                    ("goal", "Goal Celebration"),
                    ("score_update", "Score Update"),
                    ("end_score", "Final Score"),
                    ("match_summary", "Match Summary"),
                    ("highlights", "Highlights Reel"),
                    ("transformation", "Then vs Now"),
                    ("season_recap", "Season Recap"),
                    ("profile_photo", "Profile Photo"),
                    ("legacy_photo", "Legacy Photo"),
                    ("closeup", "Close-up"),
                    ("member_intro", "Short Intro"),
                    ("member_goal_celebration", "Goal Celebration"),
                    ("member_in_tenue", "In Tenue"),
                    ("member_legacy_closeup", "Legacy Closeup"),
                    ("member_legacy_in_tenue", "Legacy In Tenue"),
                    ("member_action_photo", "Action Photo"),
                    ("custom_logo", "Logo"),
                    ("custom_tenue", "Tenue"),
                    ("custom_tenue_logo", "Tenue + Logo"),
                    ("custom_tenue_logo_sponsor", "Tenue + Logo + Sponsor"),
                ],
                db_index=True,
                help_text="Specific template type (what)",
                max_length=50,
                null=True,
            ),
        ),
    ]
