# Generated by Django 5.1.4 on 2026-01-06 07:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organisations", "0002_add_enable_theme_toggle"),
        ("projects", "0002_projectinvite_projectmembership_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='Activity title (e.g., "Ajax vs Feyenoord")', max_length=200
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        help_text="Flexible type field (match, meeting, training, lecture, etc.)",
                        max_length=50,
                    ),
                ),
                ("start_time", models.DateTimeField(help_text="Activity start (timezone-aware)")),
                ("end_time", models.DateTimeField(help_text="Activity end (timezone-aware)")),
                ("location", models.CharField(blank=True, default="", max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Outcome data (score, goals, meeting notes, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Activities",
                "db_table": "activities_activity",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Display name (e.g., "Seizoen 2023/2024")', max_length=200
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("start_date", models.DateField(help_text="Period start (date only, no timezone)")),
                ("end_date", models.DateField(help_text="Period end (date only, no timezone)")),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible storage for domain-specific attributes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "parent_period",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent in hierarchy. NULL = root period.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="activities.period",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional project scope. If null, period is organisation-wide.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "activities_period",
                "ordering": ["start_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="Flexible role field (squad_member, captain, starter, substitute, attendee, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("tentative", "Tentative"),
                            ("declined", "Declined"),
                            ("no_response", "No Response"),
                        ],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Role-specific metadata (jersey_number, position, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        help_text="Activity participation (mutually exclusive with period)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="activities.activity",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="Organisation membership (not User)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="organisations.membership",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        blank=True,
                        help_text="Period participation (mutually exclusive with activity)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="activities.period",
                    ),
                ),
            ],
            options={
                "db_table": "activities_participation",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="activities.period",
            ),
        ),
        migrations.AddIndex(
            model_name="period",
            index=models.Index(
                fields=["organisation", "project"], name="activities__organis_d76084_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="period",
            index=models.Index(fields=["parent_period"], name="activities__parent__c1ee76_idx"),
        ),
        migrations.AddIndex(
            model_name="period",
            index=models.Index(
                fields=["start_date", "end_date"], name="activities__start_d_a4ba70_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="period",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gt", models.F("start_date"))),
                name="period_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="period",
            constraint=models.UniqueConstraint(
                fields=("organisation", "name", "start_date"), name="unique_period_per_org"
            ),
        ),
        migrations.AddIndex(
            model_name="participation",
            index=models.Index(fields=["member", "period"], name="activities__member__3d80b8_idx"),
        ),
        migrations.AddIndex(
            model_name="participation",
            index=models.Index(
                fields=["member", "activity"], name="activities__member__777767_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="participation",
            index=models.Index(fields=["role", "status"], name="activities__role_f0fa07_idx"),
        ),
        migrations.AddConstraint(
            model_name="participation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("activity__isnull", False), ("period__isnull", True)),
                    models.Q(("activity__isnull", True), ("period__isnull", False)),
                    _connector="OR",
                ),
                name="participation_activity_xor_period",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="participation",
            unique_together={("member", "activity"), ("member", "period")},
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["project", "period", "start_time"], name="activities__project_0f7d11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["activity_type"], name="activities__activit_8e7970_idx"),
        ),
        migrations.AddConstraint(
            model_name="activity",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))),
                name="activity_end_after_start",
            ),
        ),
    ]
