# Generated by Django 5.1.4 on 2026-01-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="data",
        ),
        migrations.RemoveField(
            model_name="period",
            name="data",
        ),
        migrations.AddField(
            model_name="activity",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Flexible storage (opponent, score, is_home, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="period",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Flexible storage for domain-specific attributes",
            ),
        ),
    ]
