# Generated by Django 5.1.4 on 2026-01-07 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0002_add_metadata_fields"),
        ("projects", "0003_add_metadata_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="opponent_project",
            field=models.ForeignKey(
                blank=True,
                help_text="Opponent team/project (for match activities)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opponent_activities",
                to="projects.project",
            ),
        ),
    ]
