# Generated by Django 5.1.4 on 2026-01-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0005_activityevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="slug",
            field=models.SlugField(blank=True, max_length=240, null=True, unique=True),
        ),
    ]
