# Generated by Django 5.1.4 on 2026-01-30 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0006_activity_slug"),
        ("sport_configuration", "0003_add_sport_hierarchy"),
    ]

    operations = [
        migrations.AddField(
            model_name="period",
            name="sport",
            field=models.ForeignKey(
                blank=True,
                help_text="Sport variant for this period (typically set on Competition, not Season).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="periods",
                to="sport_configuration.sport",
            ),
        ),
    ]
