# Generated by Django 5.1.4 on 2026-03-20 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0008_period_period_type"),
        ("organisations", "0004_add_sport_to_organisation"),
        ("projects", "0018_b46_soft_delete_mixin"),
        ("sport_configuration", "0005_add_formation_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Timestamp when this record was soft-deleted (NULL = active)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who soft-deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="participation",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Timestamp when this record was soft-deleted (NULL = active)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="participation",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who soft-deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="period",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Timestamp when this record was soft-deleted (NULL = active)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="period",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who soft-deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["deleted_at"], name="activities__deleted_783a77_idx"),
        ),
        migrations.AddIndex(
            model_name="participation",
            index=models.Index(fields=["deleted_at"], name="activities__deleted_f46624_idx"),
        ),
        migrations.AddIndex(
            model_name="period",
            index=models.Index(fields=["deleted_at"], name="activities__deleted_07ca14_idx"),
        ),
    ]
