# Generated by Django 5.1.4 on 2026-04-01 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0009_soft_delete_extension"),
        ("projects", "0018_b46_soft_delete_mixin"),
        ("sport_configuration", "0005_add_formation_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="formation",
            field=models.ForeignKey(
                blank=True,
                help_text="Formation/tactiek gebruikt voor deze wedstrijd",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="sport_configuration.formation",
            ),
        ),
        migrations.AddField(
            model_name="participation",
            name="project_membership",
            field=models.ForeignKey(
                blank=True,
                help_text="Project membership (team + seizoen) for lineup resolution",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participations",
                to="projects.projectmembership",
            ),
        ),
    ]
