# Generated by Django 5.1.4 on 2026-02-01 15:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("files", "0002_add_thumbnail_path"),
        ("organisations", "0004_add_sport_to_organisation"),
        ("projects", "0015_project_sport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this brand profile", max_length=200
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive profiles are preserved but not returned in API responses",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_brand_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organisation-level brand (null for project-specific brands)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_profiles",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project-level brand (null for organisation-level brands)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_profiles",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_brand_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand Profile",
                "verbose_name_plural": "Brand Profiles",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="BrandAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("logo_light", "Logo (Light Mode)"),
                            ("logo_dark", "Logo (Dark Mode)"),
                            ("watermark", "Watermark"),
                            ("favicon", "Favicon"),
                            ("font_file", "Font File"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, help_text="Accessibility text for images", max_length=255
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.ForeignKey(
                        help_text="B22 FileAsset reference (PROTECT to prevent accidental deletion)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="brand_assets",
                        to="files.fileasset",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_assets",
                        to="branding.brandprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand Asset",
                "verbose_name_plural": "Brand Assets",
                "ordering": ["asset_type"],
            },
        ),
        migrations.CreateModel(
            name="DesignToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Token key (e.g., primary_color, font_heading)", max_length=100
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Token value (e.g., #FF0000, Roboto, 16px)", max_length=1000
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("color", "Color"),
                            ("font", "Font"),
                            ("spacing", "Spacing"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional documentation for this token", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_tokens",
                        to="branding.brandprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Design Token",
                "verbose_name_plural": "Design Tokens",
                "ordering": ["type", "key"],
            },
        ),
        migrations.AddIndex(
            model_name="brandprofile",
            index=models.Index(fields=["organisation"], name="branding_br_organis_510e04_idx"),
        ),
        migrations.AddIndex(
            model_name="brandprofile",
            index=models.Index(fields=["project"], name="branding_br_project_8d88ea_idx"),
        ),
        migrations.AddConstraint(
            model_name="brandprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("organisation__isnull", False), ("project__isnull", True)),
                    models.Q(("organisation__isnull", True), ("project__isnull", False)),
                    _connector="OR",
                ),
                name="brand_profile_org_xor_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="brandprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organisation__isnull", False)),
                fields=("organisation",),
                name="unique_brand_per_organisation",
            ),
        ),
        migrations.AddConstraint(
            model_name="brandprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("project__isnull", False)),
                fields=("project",),
                name="unique_brand_per_project",
            ),
        ),
        migrations.AddIndex(
            model_name="brandasset",
            index=models.Index(
                fields=["profile", "asset_type"], name="branding_br_profile_d1569a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="brandasset",
            constraint=models.UniqueConstraint(
                fields=("profile", "asset_type"), name="unique_asset_type_per_profile"
            ),
        ),
        migrations.AddIndex(
            model_name="designtoken",
            index=models.Index(fields=["profile", "key"], name="branding_de_profile_907f01_idx"),
        ),
        migrations.AddIndex(
            model_name="designtoken",
            index=models.Index(fields=["type"], name="branding_de_type_99e97c_idx"),
        ),
        migrations.AddConstraint(
            model_name="designtoken",
            constraint=models.UniqueConstraint(
                fields=("profile", "key"), name="unique_token_key_per_profile"
            ),
        ),
    ]
