# Generated by Django 5.1.4 on 2026-02-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branding", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brandasset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("logo_light", "Logo (Light Mode)"),
                    ("logo_dark", "Logo (Dark Mode)"),
                    ("watermark", "Watermark"),
                    ("favicon", "Favicon"),
                    ("font_file", "Font File"),
                    ("kit_home", "Home Kit"),
                    ("kit_away", "Away Kit"),
                    ("kit_third", "Third Kit"),
                    ("kit_goalkeeper", "Goalkeeper Kit"),
                    ("kit_coach", "Coach Kit"),
                    ("kit_assistant", "Assistant Kit"),
                    ("kit_training", "Training Kit"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
