# Generated by Django 5.1.4 on 2026-02-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branding", "0002_add_kit_asset_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brandasset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("logo_upload", "Logo (Raw Upload)"),
                    ("logo_light", "Logo (Light Mode - AI Processed)"),
                    ("logo_dark", "Logo (Dark Mode - AI Processed)"),
                    ("watermark", "Watermark"),
                    ("favicon", "Favicon"),
                    ("font_file", "Font File"),
                    ("sponsor_logo_upload", "Sponsor Logo (Raw Upload)"),
                    ("sponsor_logo", "Sponsor Logo (AI Processed)"),
                    ("kit_home_upload", "Home Kit (Raw Upload)"),
                    ("kit_home", "Home Kit (AI Processed)"),
                    ("kit_home_combined", "Home Kit (Combined: Kit+Logo+Sponsor)"),
                    ("kit_away_upload", "Away Kit (Raw Upload)"),
                    ("kit_away", "Away Kit (AI Processed)"),
                    ("kit_away_combined", "Away Kit (Combined: Kit+Logo+Sponsor)"),
                    ("kit_third_upload", "Third Kit (Raw Upload)"),
                    ("kit_third", "Third Kit (AI Processed)"),
                    ("kit_third_combined", "Third Kit (Combined: Kit+Logo+Sponsor)"),
                    ("kit_goalkeeper_upload", "Goalkeeper Kit (Raw Upload)"),
                    ("kit_goalkeeper", "Goalkeeper Kit (AI Processed)"),
                    ("kit_goalkeeper_combined", "Goalkeeper Kit (Combined: Kit+Logo+Sponsor)"),
                    ("kit_coach_upload", "Coach Kit (Raw Upload)"),
                    ("kit_coach", "Coach Kit (AI Processed)"),
                    ("kit_coach_combined", "Coach Kit (Combined: Kit+Logo+Sponsor)"),
                    ("kit_assistant_upload", "Assistant Kit (Raw Upload)"),
                    ("kit_assistant", "Assistant Kit (AI Processed)"),
                    ("kit_assistant_combined", "Assistant Kit (Combined: Kit+Logo+Sponsor)"),
                    ("kit_training_upload", "Training Kit (Raw Upload)"),
                    ("kit_training", "Training Kit (AI Processed)"),
                    ("kit_training_combined", "Training Kit (Combined: Kit+Logo+Sponsor)"),
                    ("location_photo", "Location Photo"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
