# Generated by Django 5.1.4 on 2026-03-16 16:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branding", "0007_add_club_background_upload_type"),
        ("files", "0002_add_thumbnail_path"),
        ("sport_configuration", "0005_add_formation_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppBackground",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display name shown in picker (e.g. 'Voetbalveld', 'Grasmat avond')",
                        max_length=100,
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, help_text="Lower = shown first in picker"),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        help_text="Background image file",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="app_backgrounds",
                        to="files.fileasset",
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        help_text="Sport category this background belongs to (e.g. Football)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_backgrounds",
                        to="sport_configuration.sport",
                    ),
                ),
            ],
            options={
                "verbose_name": "App Background",
                "verbose_name_plural": "App Backgrounds",
                "ordering": ["sort_order", "label"],
            },
        ),
    ]
