# Generated by Django 5.1.4 on 2026-02-02 19:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("activities", "0007_add_sport_to_period"),
        ("files", "0002_add_thumbnail_path"),
        ("generative", "0002_change_file_id_to_uuid"),
        ("projects", "0015_project_sport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_collections",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "medialib_collections",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("mime_type", models.CharField(max_length=127)),
                ("file_size_bytes", models.BigIntegerField()),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("raw", "Raw Upload"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("error", "Error"),
                            ("archived", "Archived"),
                        ],
                        default="raw",
                        max_length=20,
                    ),
                ),
                ("extraction_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="activities.activity",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="files.fileasset"
                    ),
                ),
                (
                    "generation_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="generative.generationrequest",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_items",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "medialib_items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CollectionMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="medialib35.collection"
                    ),
                ),
                (
                    "media_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="medialib35.mediaitem"
                    ),
                ),
            ],
            options={
                "db_table": "medialib_collection_membership",
                "ordering": ["position", "added_at"],
                "unique_together": {("collection", "media_item")},
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="items",
            field=models.ManyToManyField(
                related_name="collections",
                through="medialib35.CollectionMembership",
                to="medialib35.mediaitem",
            ),
        ),
        migrations.CreateModel(
            name="MediaTag",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("is_system", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_tags",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "medialib_tags",
                "ordering": ["name"],
                "unique_together": {("project", "slug")},
            },
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="items", to="medialib35.mediatag"
            ),
        ),
        migrations.AddIndex(
            model_name="mediaitem",
            index=models.Index(
                fields=["project", "-created_at"], name="medialib_it_project_a8d9a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediaitem",
            index=models.Index(fields=["state"], name="medialib_it_state_367976_idx"),
        ),
    ]
