# Generated by Django 5.1.4 on 2026-01-03 10:36

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        TrigramExtension(),
    ]
