# Generated by Django 5.1.4 on 2026-01-03 10:37

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("search", "0001_enable_pg_trgm"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("object_id", models.UUIDField()),
                ("search_vector", django.contrib.postgres.search.SearchVectorField()),
                ("body_text", models.TextField(help_text="Full text content for highlighting")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("url", models.CharField(help_text="Relative URL to the resource", max_length=500)),
                (
                    "language",
                    models.CharField(
                        default="english", help_text="Language used for stemming", max_length=50
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Search entries",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="search_sear_search__5549f6_gin"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "object_id"), name="unique_search_entry"
                    )
                ],
            },
        ),
    ]
