# Generated by Django 5.1.4 on 2026-01-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0002_create_search_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchentry",
            name="object_id",
            field=models.CharField(max_length=255),
        ),
    ]
