# Generated by Django 5.1.4 on 2025-12-04 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contextual_notifications", "0002_seed_default_routing_rules"),
        ("organisations", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="organisationnotificationpolicy",
            name="org_policy_quiet_hours_consistency",
        ),
        migrations.RemoveConstraint(
            model_name="routingrule",
            name="routing_rule_scope_consistency",
        ),
        migrations.RenameIndex(
            model_name="notificationpreference",
            new_name="contextual__user_id_403020_idx",
            old_name="contextual_notific_user_id_event_t_idx",
        ),
        migrations.RenameIndex(
            model_name="routingrule",
            new_name="contextual__event_t_d570be_idx",
            old_name="contextual_routing_ev_event_t_idx",
        ),
        migrations.RenameIndex(
            model_name="routingrule",
            new_name="contextual__event_t_67fe8c_idx",
            old_name="contextual_routing_ev_event_s_idx",
        ),
        migrations.AddConstraint(
            model_name="organisationnotificationpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quiet_hours_enabled", False),
                    models.Q(
                        ("quiet_hours_enabled", True),
                        ("quiet_hours_end__isnull", False),
                        ("quiet_hours_start__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="org_policy_quiet_hours_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="routingrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("organisation__isnull", True),
                        ("project__isnull", True),
                        ("scope", "global"),
                    ),
                    models.Q(
                        ("organisation__isnull", False), ("project__isnull", True), ("scope", "org")
                    ),
                    models.Q(
                        ("organisation__isnull", False),
                        ("project__isnull", False),
                        ("scope", "project"),
                    ),
                    _connector="OR",
                ),
                name="routing_rule_scope_consistency",
            ),
        ),
    ]
