# Generated by Django 5.1.4 on 2025-11-28 17:42

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organisations", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, db_index=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usage_events",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usage_events",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usage_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("usage_event", "Usage Event"),
                            ("adjustment", "Adjustment"),
                            ("external_billing", "External Billing"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "external_reference_id",
                    models.CharField(blank=True, db_index=True, max_length=255, null=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="projects.project",
                    ),
                ),
                (
                    "usage_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="transactions.usageevent",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="BalancePolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "allow_negative",
                    models.BooleanField(
                        default=False,
                        help_text="Can balance go negative? False=prepaid, True=postpaid",
                    ),
                ),
                (
                    "warn_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Balance level to trigger warnings",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "enforcement_mode",
                    models.CharField(
                        choices=[("block", "Block"), ("warn", "Warn"), ("allow", "Allow")],
                        default="block",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_policies",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_policies",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Balance policies",
                "indexes": [
                    models.Index(
                        condition=models.Q(("project__isnull", True)),
                        fields=["organization"],
                        name="balpol_org_idx",
                    ),
                    models.Index(
                        condition=models.Q(("project__isnull", False)),
                        fields=["project"],
                        name="balpol_proj_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "project"), name="balpol_org_proj_unique"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="usageevent",
            index=models.Index(fields=["organization", "-timestamp"], name="usevt_org_ts_idx"),
        ),
        migrations.AddIndex(
            model_name="usageevent",
            index=models.Index(
                condition=models.Q(("project__isnull", False)),
                fields=["project", "-timestamp"],
                name="usevt_proj_ts_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usageevent",
            index=models.Index(fields=["event_type", "-timestamp"], name="usevt_type_ts_idx"),
        ),
        migrations.AddConstraint(
            model_name="usageevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("idempotency_key",),
                name="usevt_idem_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["organization", "-timestamp"], name="txn_org_ts_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                condition=models.Q(("project__isnull", False)),
                fields=["project", "-timestamp"],
                name="txn_proj_ts_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["source_type", "-timestamp"], name="txn_src_ts_idx"),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount", Decimal("0")), _negated=True),
                name="txn_amount_nonzero",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("source_type", "usage_event"), ("usage_event__isnull", False)),
                    models.Q(("source_type", "usage_event"), _negated=True),
                    _connector="OR",
                ),
                name="txn_usage_evt_src_match",
            ),
        ),
    ]
