# Generated by Django 5.1.4 on 2026-01-16 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0003_add_metadata_fields"),
        ("projects", "0011_alter_projectfunctionalroleassignment_assignment_reason_and_more"),
        ("transactions", "0002_wallet_scope_and_charged_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                condition=models.Q(("charged_user__isnull", False)),
                fields=["charged_user", "-timestamp"],
                name="txn_user_ts_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["wallet_scope", "-timestamp"], name="txn_scope_ts_idx"),
        ),
    ]
