[program:celery-beat]
command=/opt/django-core-app/venv/bin/celery -A config beat -l info
directory=/opt/django-core-app
user=django
numprocs=1
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=30
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/celery/beat.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
environment=DJANGO_SETTINGS_MODULE="config.settings.production",CELERY_BROKER_URL="redis://localhost:6379/0",PYTHONPATH="/opt/django-core-app"

; Priority ensures beat starts after workers
priority=999
