# Generated by Django 5.1.4 on 2026-03-19 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("organisations", "0004_add_sport_to_organisation"),
        ("projects", "0017_project_team_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "verb",
                    models.CharField(
                        db_index=True,
                        help_text="Machine-readable event type, e.g. 'content.created'.",
                        max_length=50,
                    ),
                ),
                ("target_object_id", models.UUIDField(blank=True, null=True)),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Context-specific information, e.g. {'old_status': 'draft', 'new_status': 'approved'}.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the event.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        help_text="Organisation this event belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional project scope for filtering.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="projects.project",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_log_targets",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "db_table": "activity_feed_activitylog",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organisation", "-created_at"], name="actfeed_org_created_desc"
                    ),
                    models.Index(
                        fields=["organisation", "project", "-created_at"],
                        name="actfeed_org_proj_created",
                    ),
                    models.Index(
                        fields=["organisation", "verb", "-created_at"],
                        name="actfeed_org_verb_created",
                    ),
                    models.Index(
                        fields=["target_content_type", "target_object_id"],
                        name="actfeed_target_gfk",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FeedPosition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "last_read_at",
                    models.DateTimeField(
                        help_text="Timestamp of the newest event the user has seen."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_positions",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_positions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feed Position",
                "verbose_name_plural": "Feed Positions",
                "db_table": "activity_feed_feedposition",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "organisation"), name="unique_feed_position_per_user_org"
                    )
                ],
            },
        ),
    ]
