# Generated by Django 5.1.4 on 2026-03-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity_feed", "0001_initial_activity_feed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="target_object_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
