# Generated by Django 5.1.4 on 2026-04-02 14:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("activities", "0010_add_formation_and_project_membership"),
        ("projects", "0018_b46_soft_delete_mixin"),
        ("video", "0005_alter_videojob_job_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkGenerationJob",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when this record was soft-deleted (NULL = active)",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("partially_completed", "Partially Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        help_text="Current status of the bulk job",
                        max_length=25,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("lineup", "Lineup Video"),
                            ("lineup_flyer", "Lineup Flyer"),
                            ("match_intro", "Match Intro"),
                            ("goal_celebration", "Goal Celebration"),
                            ("then_vs_now", "Then vs Now"),
                            ("match_flyer", "Match Flyer"),
                        ],
                        help_text="Type of content being generated",
                        max_length=30,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional config: template_id, style_variant, etc.",
                    ),
                ),
                (
                    "total_items",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of items in this batch"
                    ),
                ),
                (
                    "completed_items",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of successfully completed items"
                    ),
                ),
                (
                    "failed_items",
                    models.PositiveIntegerField(default=0, help_text="Number of failed items"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When processing started", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When all items finished", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who initiated the bulk generation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_generation_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who soft-deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project (team) this bulk job belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_generation_jobs",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BulkGenerationItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current status of this item",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, default="", help_text="Error details if generation failed"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Per-item config overrides"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "activity",
                    models.ForeignKey(
                        help_text="Activity (match) this item generates content for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_generation_items",
                        to="activities.activity",
                    ),
                ),
                (
                    "video_job",
                    models.ForeignKey(
                        blank=True,
                        help_text="Created VideoJob (once dispatched)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_generation_items",
                        to="video.videojob",
                    ),
                ),
                (
                    "bulk_job",
                    models.ForeignKey(
                        help_text="Parent bulk generation job",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="bulk_generation.bulkgenerationjob",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="bulkgenerationjob",
            index=models.Index(
                fields=["project", "-created_at"], name="bulk_genera_project_6bb459_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bulkgenerationjob",
            index=models.Index(fields=["status"], name="bulk_genera_status_70658d_idx"),
        ),
        migrations.AddIndex(
            model_name="bulkgenerationitem",
            index=models.Index(
                fields=["bulk_job", "status"], name="bulk_genera_bulk_jo_24d63d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bulkgenerationitem",
            constraint=models.UniqueConstraint(
                fields=("bulk_job", "activity"), name="unique_activity_per_bulk_job"
            ),
        ),
    ]
