"""
TeamReel V4 Pipeline: Hybrid Composite Kit
==========================================

Strategy:
1. GENERATE BASE: Create a flawless, minimalist blank kit using AI (Imagen 4 Ultra).
   - Explicitly: White Shirt, Blue Shorts, Blue Socks.
   - Style: Flat lay, vector style, white background.
   - NO logos or text generated by AI.

2. COMPOSITE: Use Python (Pillow) to overlay the ORIGINAL logo and sponsor.
   - This ensures brand identity is preserved 100%.
   - Includes transparency handling for clean integration.
"""

import os
import sys
from pathlib import Path
from PIL import Image, ImageOps

# Paths
INPUT_DIR = Path("asc/input")
OUTPUT_DIR = Path("asc/output_v4")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

try:
    from google import genai
    from google.genai import types
except ImportError:
    print("❌ install google-genai first")
    sys.exit(1)

client = genai.Client(api_key=os.environ.get("GOOGLE_API_KEY"))

# =============================================================================
# HELPER: IMAGE PROCESSING
# =============================================================================
def make_transparent(img):
    """Convert white background to transparent."""
    img = img.convert("RGBA")
    datas = img.getdata()
    new_data = []
    for item in datas:
        # If pixel is very light/white, make it transparent
        if item[0] > 240 and item[1] > 240 and item[2] > 240:
            new_data.append((255, 255, 255, 0))
        else:
            new_data.append(item)
    img.putdata(new_data)
    return img

def resize_to_width(img, width):
    wpercent = (width / float(img.size[0]))
    hsize = int((float(img.size[1]) * float(wpercent)))
    return img.resize((width, hsize), Image.Resampling.LANCZOS)

# =============================================================================
# STEP 1: GENERATE BLANK KIT
# =============================================================================
def generate_blank_kit():
    print("\n🎨 STEP 1: Generating Blank Component Kit...")
    print("-" * 50)

    # Prompt specific for a blank template
    prompt = """Create a minimalist BLANK football kit template (Flat Lay).

    COMPONENTS:
    - Shirt: WHITE long-sleeve shirt with BLUE crew neck collar and BLUE sleeve cuffs.
    - Shorts: BLUE (Royal/Azure Blue).
    - Socks: BLUE (Royal/Azure Blue) knee-high socks.

    STYLE:
    - Flat Lay arrangement: Shirt in center, Shorts below, Socks on sides.
    - Style: Clean 2D Vector Illustration / Digital Mockup.
    - Background: Pure White.
    - NO logos, NO text, NO sponsors. Just the blank fabric.
    - NO shadows, NO gradients.
    """

    try:
        response = client.models.generate_images(
            model='imagen-4.0-ultra-generate-001',
            prompt=prompt,
            config=types.GenerateImagesConfig(
                number_of_images=1,
                aspect_ratio='4:3',
                safety_filter_level='BLOCK_LOW_AND_ABOVE',
            )
        )
        if response.generated_images:
            out_path = OUTPUT_DIR / 'base_kit.png'
            response.generated_images[0].image.save(str(out_path))
            print(f"   ✅ Saved Base Kit: {out_path}")
            return out_path
    except Exception as e:
        print(f"   ❌ Generation Error: {e}")
        return None

# =============================================================================
# STEP 2: COMPOSITE LOGOS
# =============================================================================
def composite_kit(base_kit_path):
    print("\n🛠️ STEP 2: Compositing Logos onto Kit...")
    print("-" * 50)

    # Load Base
    try:
        base = Image.open(base_kit_path).convert("RGBA")
    except Exception as e:
        print(f"   ❌ Could not load base kit: {e}")
        return

    width, height = base.size
    print(f"   📏 Canvas Size: {width}x{height}")

    # Load & Prep Club Logo
    try:
        logo_path = INPUT_DIR / "logo.png"
        if not logo_path.exists():
             logo_path = Path("asc/asc logo raw.png") # Fallback

        logo = Image.open(logo_path)
        logo = make_transparent(logo)

        # Resize logo (approx 10-12% of shirt width)
        target_logo_width = int(width * 0.08)
        logo = resize_to_width(logo, target_logo_width)

        # Position: Left Chest (Right side of image, upper third of shirt)
        # Approximate coordinates for a flat lay 4:3 image
        logo_x = int(width * 0.55)
        logo_y = int(height * 0.28)

        print(f"   🛡️ Placing Logo at ({logo_x}, {logo_y})")
        base.paste(logo, (logo_x, logo_y), logo)
    except Exception as e:
        print(f"   ⚠️ Logo compositing failed: {e}")

    # Load & Prep Sponsor
    try:
        sponsor_path = INPUT_DIR / "sponsor.png"
        if not sponsor_path.exists():
            print("   ⚠️ Sponsor image not found in input/")
        else:
            sponsor = Image.open(sponsor_path)
            sponsor = make_transparent(sponsor)

            # Resize sponsor (approx 25-30% of shirt width)
            target_sponsor_width = int(width * 0.25)
            sponsor = resize_to_width(sponsor, target_sponsor_width)

            # Position: Center Chest
            sponsor_x = int((width / 2) - (target_sponsor_width / 2)) # Centered horizontally
            sponsor_y = int(height * 0.35) # Middle of shirt

            print(f"   🤝 Placing Sponsor at ({sponsor_x}, {sponsor_y})")
            base.paste(sponsor, (sponsor_x, sponsor_y), sponsor)

    except Exception as e:
        print(f"   ⚠️ Sponsor compositing failed: {e}")

    # Save Final
    final_output = OUTPUT_DIR / "final_composite_kit.png"
    base.save(final_output, format="PNG")
    print(f"\n✅ SUCCESS! Final Kit Saved: {final_output}")

if __name__ == "__main__":
    print("🚀 Starting V4 Composite Pipeline...")

    # 1. Generate Blank
    base_path = generate_blank_kit()

    # 2. Composite
    if base_path:
        composite_kit(base_path)
