# Generated by Django 5.1.4 on 2025-11-25 13:00

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organisations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Human-readable project name", max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier (auto-generated from name if not provided)",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional project description (up to 2000 characters)",
                        max_length=2000,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="False when project is archived (soft deletion)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when project was archived (NULL if active)",
                        null=True,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="User who created this project",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        help_text="Organisation that owns this project",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "db_table": "projects_project",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organisation", "is_active"], name="projects_pr_organis_160248_idx"
                    ),
                    models.Index(fields=["slug"], name="projects_pr_slug_042165_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "slug"), name="unique_project_slug_per_org"
                    ),
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        models.F("organisation"),
                        name="unique_project_name_per_org_case_insensitive",
                    ),
                ],
            },
        ),
    ]
