# Generated by Django 5.1.4 on 2026-01-04 16:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0002_add_enable_theme_toggle"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address of the invited user", max_length=254
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("viewer", "Viewer"), ("editor", "Editor"), ("admin", "Admin")],
                        default="viewer",
                        help_text="Role to be assigned upon acceptance",
                        max_length=20,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        editable=False,
                        help_text="Secure token for invitation acceptance",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        help_text="Current status of the invitation",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(help_text="Timestamp when invitation expires")),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when invitation was accepted", null=True
                    ),
                ),
            ],
            options={
                "db_table": "projects_invite",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("viewer", "Viewer"), ("editor", "Editor"), ("admin", "Admin")],
                        default="viewer",
                        help_text="Access level for this user in this project",
                        max_length=20,
                    ),
                ),
                (
                    "assignment_reason",
                    models.CharField(
                        choices=[
                            ("manual", "Manually Added"),
                            ("invitation", "Accepted Invitation"),
                            ("promotion", "Promoted"),
                            ("org_default", "Organisation Default"),
                        ],
                        default="manual",
                        help_text="How this membership was created",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when membership was revoked (soft delete)",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "projects_membership",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMembershipPromotion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "from_role",
                    models.CharField(
                        choices=[("viewer", "Viewer"), ("editor", "Editor"), ("admin", "Admin")],
                        help_text="Current role of the user",
                        max_length=20,
                    ),
                ),
                (
                    "to_role",
                    models.CharField(
                        choices=[("viewer", "Viewer"), ("editor", "Editor"), ("admin", "Admin")],
                        help_text="Proposed new role",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of the promotion request",
                        max_length=20,
                    ),
                ),
                (
                    "is_suspicious",
                    models.BooleanField(
                        default=False,
                        help_text="Flagged if promotion happens shortly after joining",
                    ),
                ),
                (
                    "suspicious_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason why this promotion was flagged as suspicious",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(help_text="Timestamp when request expires")),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when request was resolved", null=True
                    ),
                ),
            ],
            options={
                "db_table": "projects_promotion",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="is_private",
            field=models.BooleanField(
                default=False,
                help_text="If True, project is only accessible to explicit members (no org-wide access)",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["organisation", "is_private"], name="projects_pr_organis_66e40e_idx"
            ),
        ),
        migrations.AddField(
            model_name="projectinvite",
            name="invited_by",
            field=models.ForeignKey(
                help_text="User who sent the invitation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_project_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectinvite",
            name="project",
            field=models.ForeignKey(
                help_text="Project the user is invited to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="projectmembership",
            name="project",
            field=models.ForeignKey(
                help_text="Project this membership belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="projectmembership",
            name="user",
            field=models.ForeignKey(
                help_text="User who holds this membership",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectmembershippromotion",
            name="project",
            field=models.ForeignKey(
                help_text="Project where promotion is requested",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotions",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="projectmembershippromotion",
            name="requested_by",
            field=models.ForeignKey(
                help_text="Admin who initiated the promotion",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_promotions_initiated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectmembershippromotion",
            name="target_user",
            field=models.ForeignKey(
                help_text="User being promoted",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_promotions_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="projectinvite",
            index=models.Index(fields=["email", "status"], name="projects_in_email_c4fb17_idx"),
        ),
        migrations.AddIndex(
            model_name="projectinvite",
            index=models.Index(fields=["token"], name="projects_in_token_c890b7_idx"),
        ),
        migrations.AddIndex(
            model_name="projectinvite",
            index=models.Index(fields=["project", "status"], name="projects_in_project_376859_idx"),
        ),
        migrations.AddIndex(
            model_name="projectmembership",
            index=models.Index(
                fields=["project", "deleted_at"], name="projects_me_project_ef458f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectmembership",
            index=models.Index(
                fields=["user", "deleted_at"], name="projects_me_user_id_1c4a04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectmembership",
            index=models.Index(
                fields=["project", "role", "deleted_at"], name="projects_me_project_5a93ca_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("project", "user"),
                name="unique_active_project_membership",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectmembership",
            unique_together={("project", "user")},
        ),
        migrations.AddIndex(
            model_name="projectmembershippromotion",
            index=models.Index(
                fields=["target_user", "status"], name="projects_pr_target__489623_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectmembershippromotion",
            index=models.Index(fields=["project", "status"], name="projects_pr_project_42fd98_idx"),
        ),
    ]
