# Generated by Django 5.1.4 on 2026-01-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_projectinvite_projectmembership_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Flexible master data storage (e.g., stadium, city, team colors)",
            ),
        ),
    ]
