# Generated by Django 5.1.4 on 2026-01-07 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0003_add_teamreel_hierarchy"),
        ("projects", "0003_add_metadata_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="parent_project",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent project (e.g., Club for a Team). NULL = root level.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="projectmembership",
            name="period",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional period/season scope (e.g., player in 2024/2025 season)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_memberships",
                to="activities.period",
            ),
        ),
    ]
