# Generated by Django 5.1.4 on 2026-01-07 21:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_update_membership_constraint"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="projectmembership",
            unique_together=set(),
        ),
    ]
