# Generated by Django 5.1.4 on 2026-01-16 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_project_functional_roles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectfunctionalroleassignment",
            name="assignment_reason",
            field=models.CharField(
                choices=[("manual", "Manual"), ("imported", "Imported")],
                default="manual",
                help_text="How this assignment was created",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projectfunctionalroleassignment",
            name="project",
            field=models.ForeignKey(
                help_text="Project/team this functional role applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="functional_role_assignments",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="projectfunctionalroleassignment",
            name="role",
            field=models.CharField(
                choices=[
                    ("coach", "Coach"),
                    ("player", "Player"),
                    ("keeper", "Keeper"),
                    ("assistant", "Assistant"),
                    ("verzorger", "Verzorger"),
                    ("supporter", "Supporter"),
                    ("manager", "Manager"),
                ],
                help_text="Functional (domain) role on the team",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="projectfunctionalroleassignment",
            name="user",
            field=models.ForeignKey(
                help_text="User who holds this functional role",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_functional_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
