# Generated by GitHub Copilot on 2026-01-23

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0012_update_project_name_constraints"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="project",
            name="unique_project_slug_per_org",
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("organisation", "slug"),
                condition=Q(parent_project__isnull=True),
                name="unique_root_project_slug_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("organisation", "parent_project", "slug"),
                condition=Q(parent_project__isnull=False),
                name="unique_child_project_slug_per_parent",
            ),
        ),
    ]
