# Generated by Django 5.1.4 on 2026-01-30 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0014_restore_unique_active_project_membership"),
        ("sport_configuration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="sport",
            field=models.ForeignKey(
                blank=True,
                help_text="Sport/discipline for this project. Teams can inherit from parent club.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="sport_configuration.sport",
            ),
        ),
    ]
