# Generated by Django 5.1.4 on 2026-02-19 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0007_add_sport_to_period"),
        ("projects", "0015_project_sport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="projectmembership",
            name="unique_active_project_membership",
        ),
        migrations.AddConstraint(
            model_name="projectmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("project", "user", "period"),
                name="unique_active_project_membership_per_period",
                nulls_distinct=False,
            ),
        ),
    ]
