# Generated by Django 5.1.4 on 2026-03-19 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0017_project_team_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmembership",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who soft-deleted this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="projectmembership",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Timestamp when this record was soft-deleted (NULL = active)",
                null=True,
            ),
        ),
    ]
