# Generated by Django 5.1.4 on 2025-12-18 17:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityEvent",
            fields=[
                (
                    "event_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action_type",
                    models.CharField(help_text="Type of action performed", max_length=50),
                ),
                (
                    "resource_type",
                    models.CharField(help_text="Type of resource affected", max_length=50),
                ),
                (
                    "resource_id",
                    models.PositiveIntegerField(help_text="ID of the affected resource"),
                ),
                ("organization_id", models.PositiveIntegerField(help_text="Organization context")),
                (
                    "project_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="Optional project context", null=True
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="When the activity occurred"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional activity-specific data"
                    ),
                ),
                (
                    "actor_user",
                    models.ForeignKey(
                        help_text="User who performed the action",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "realtime_activity_event",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["organization_id", "-occurred_at"],
                        name="realtime_ac_organiz_253eb6_idx",
                    ),
                    models.Index(
                        fields=["project_id", "-occurred_at"], name="realtime_ac_project_d29cba_idx"
                    ),
                    models.Index(
                        fields=["actor_user", "-occurred_at"], name="realtime_ac_actor_u_467f39_idx"
                    ),
                    models.Index(
                        fields=["action_type", "-occurred_at"],
                        name="realtime_ac_action__ba99f2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PresenceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("online", "Online"), ("away", "Away"), ("offline", "Offline")],
                        default="offline",
                        max_length=10,
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Last activity timestamp"
                    ),
                ),
                (
                    "current_location",
                    models.CharField(
                        blank=True,
                        help_text="Current page/project location",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "organization_id",
                    models.PositiveIntegerField(
                        help_text="Organization scope for presence visibility"
                    ),
                ),
                (
                    "project_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="Optional project scope", null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presence_statuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "realtime_presence_status",
                "indexes": [
                    models.Index(
                        fields=["organization_id", "status"], name="realtime_pr_organiz_c486f5_idx"
                    ),
                    models.Index(
                        fields=["project_id", "status"], name="realtime_pr_project_6dd7e7_idx"
                    ),
                    models.Index(fields=["last_seen"], name="realtime_pr_last_se_e49cfb_idx"),
                ],
                "unique_together": {("user", "organization_id", "project_id")},
            },
        ),
        migrations.CreateModel(
            name="RealtimeMessage",
            fields=[
                (
                    "message_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for message tracking",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("notification", "Notification Message"),
                            ("presence", "Presence Update"),
                            ("activity", "Activity Event"),
                        ],
                        help_text="Type of real-time message",
                        max_length=20,
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("user", "User Specific"),
                            ("organization", "Organization Wide"),
                            ("project", "Project Specific"),
                        ],
                        help_text="Broadcast scope level",
                        max_length=20,
                    ),
                ),
                (
                    "scope_id",
                    models.PositiveIntegerField(
                        help_text="ID of the scope (user_id, org_id, project_id)"
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        help_text="Message payload following structured envelope format"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Message creation timestamp"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, help_text="When message was successfully delivered", null=True
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Number of delivery attempts"
                    ),
                ),
                (
                    "sender_user",
                    models.ForeignKey(
                        help_text="User who triggered this message",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_realtime_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "realtime_message",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["scope_type", "scope_id", "-created_at"],
                        name="realtime_me_scope_t_104c2d_idx",
                    ),
                    models.Index(
                        fields=["message_type", "-created_at"],
                        name="realtime_me_message_d4d98c_idx",
                    ),
                    models.Index(
                        fields=["sender_user", "-created_at"], name="realtime_me_sender__ac6c0f_idx"
                    ),
                    models.Index(fields=["delivered_at"], name="realtime_me_deliver_0f402a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WebSocketConnection",
            fields=[
                (
                    "connection_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the WebSocket connection",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel_name",
                    models.CharField(
                        help_text="Django Channels channel name for message routing",
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Channel name must be alphanumeric with dots, hyphens, underscores",
                                regex="^[a-zA-Z0-9\\.\\-_]+$",
                            )
                        ],
                    ),
                ),
                (
                    "authenticated_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when connection was authenticated"
                    ),
                ),
                (
                    "last_heartbeat",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Last received heartbeat timestamp",
                    ),
                ),
                (
                    "message_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of messages sent through this connection"
                    ),
                ),
                (
                    "auth_method",
                    models.CharField(
                        choices=[
                            ("session", "Session Authentication"),
                            ("jwt", "JWT Token Authentication"),
                        ],
                        default="session",
                        help_text="Authentication method used for this connection",
                        max_length=10,
                    ),
                ),
                (
                    "client_info",
                    models.JSONField(
                        blank=True, default=dict, help_text="Browser/client metadata for debugging"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User associated with this connection",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="websocket_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "realtime_websocket_connection",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="realtime_we_user_id_66aa48_idx"
                    ),
                    models.Index(fields=["last_heartbeat"], name="realtime_we_last_he_031a34_idx"),
                    models.Index(fields=["auth_method"], name="realtime_we_auth_me_40d69f_idx"),
                ],
            },
        ),
    ]
