# Generated by Django 5.1.4 on 2025-12-18 18:08

from django.db import migrations


def create_partial_indexes(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_realtime_message_undelivered ON realtime_message(created_at) WHERE delivered_at IS NULL;"
        )


def drop_partial_indexes(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("DROP INDEX IF EXISTS idx_realtime_message_undelivered;")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("rtc_websockets", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_partial_indexes, drop_partial_indexes),
    ]
