# Generated by Django 5.1.4 on 2025-12-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rtc_websockets", "0002_partial_indexes"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE realtime_activity_event DROP CONSTRAINT IF EXISTS realtime_activity_event_organization_id_check;
            ALTER TABLE realtime_activity_event
            ALTER COLUMN organization_id TYPE uuid USING '00000000-0000-0000-0000-000000000000'::uuid;
            """,
            reverse_sql="""
            ALTER TABLE realtime_activity_event
            ALTER COLUMN organization_id TYPE integer USING 0;
            """,
            state_operations=[
                migrations.AlterField(
                    model_name="activityevent",
                    name="organization_id",
                    field=models.UUIDField(help_text="Organization context"),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE realtime_presence_status DROP CONSTRAINT IF EXISTS realtime_presence_status_organization_id_check;
            ALTER TABLE realtime_presence_status
            ALTER COLUMN organization_id TYPE uuid USING '00000000-0000-0000-0000-000000000000'::uuid;
            """,
            reverse_sql="""
            ALTER TABLE realtime_presence_status
            ALTER COLUMN organization_id TYPE integer USING 0;
            """,
            state_operations=[
                migrations.AlterField(
                    model_name="presencestatus",
                    name="organization_id",
                    field=models.UUIDField(help_text="Organization scope for presence visibility"),
                ),
            ],
        ),
    ]
