# Generated by Django 5.1.4 on 2025-12-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rtc_websockets", "0002_partial_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityevent",
            name="organization_id",
            field=models.UUIDField(help_text="Organization context"),
        ),
        migrations.AlterField(
            model_name="presencestatus",
            name="organization_id",
            field=models.UUIDField(help_text="Organization scope for presence visibility"),
        ),
    ]
