# Generated by Django 5.1.4 on 2025-12-18 20:24

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("rtc_websockets", "0003_convert_integers_to_uuid"),
    ]

    operations = [
        # ActivityEvent
        migrations.RemoveIndex(
            model_name="activityevent",
            name="realtime_ac_organiz_253eb6_idx",
        ),
        migrations.RemoveIndex(
            model_name="activityevent",
            name="realtime_ac_project_d29cba_idx",
        ),
        migrations.RemoveField(
            model_name="activityevent",
            name="organization_id",
        ),
        migrations.AddField(
            model_name="activityevent",
            name="organization_id",
            field=models.UUIDField(help_text="Organization context", default=uuid.uuid4),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="activityevent",
            name="project_id",
        ),
        migrations.AddField(
            model_name="activityevent",
            name="project_id",
            field=models.UUIDField(blank=True, help_text="Optional project context", null=True),
        ),
        migrations.RemoveField(
            model_name="activityevent",
            name="resource_id",
        ),
        migrations.AddField(
            model_name="activityevent",
            name="resource_id",
            field=models.UUIDField(help_text="ID of the affected resource", default=uuid.uuid4),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="activityevent",
            index=models.Index(
                fields=["organization_id", "-occurred_at"], name="realtime_ac_organiz_253eb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activityevent",
            index=models.Index(
                fields=["project_id", "-occurred_at"], name="realtime_ac_project_d29cba_idx"
            ),
        ),
        # PresenceStatus
        migrations.AlterUniqueTogether(
            name="presencestatus",
            unique_together=set(),
        ),
        migrations.RemoveIndex(
            model_name="presencestatus",
            name="realtime_pr_organiz_c486f5_idx",
        ),
        migrations.RemoveIndex(
            model_name="presencestatus",
            name="realtime_pr_project_6dd7e7_idx",
        ),
        migrations.RemoveField(
            model_name="presencestatus",
            name="project_id",
        ),
        migrations.AddField(
            model_name="presencestatus",
            name="project_id",
            field=models.UUIDField(blank=True, help_text="Optional project scope", null=True),
        ),
        migrations.RemoveField(
            model_name="presencestatus",
            name="organization_id",
        ),
        migrations.AddField(
            model_name="presencestatus",
            name="organization_id",
            field=models.UUIDField(
                help_text="Organization scope for presence visibility", default=uuid.uuid4
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="presencestatus",
            index=models.Index(
                fields=["organization_id", "status"], name="realtime_pr_organiz_c486f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="presencestatus",
            index=models.Index(
                fields=["project_id", "status"], name="realtime_pr_project_6dd7e7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="presencestatus",
            unique_together={("user", "organization_id", "project_id")},
        ),
        # RealtimeMessage
        migrations.RemoveIndex(
            model_name="realtimemessage",
            name="realtime_me_scope_t_104c2d_idx",
        ),
        migrations.RemoveField(
            model_name="realtimemessage",
            name="scope_id",
        ),
        migrations.AddField(
            model_name="realtimemessage",
            name="scope_id",
            field=models.UUIDField(
                help_text="ID of the scope (user_id, org_id, project_id)", default=uuid.uuid4
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="realtimemessage",
            index=models.Index(
                fields=["scope_type", "scope_id", "-created_at"],
                name="realtime_me_scope_t_104c2d_idx",
            ),
        ),
        # WebSocketConnection
        migrations.AlterField(
            model_name="websocketconnection",
            name="channel_name",
            field=models.CharField(
                help_text="Django Channels channel name for message routing",
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Channel name must be alphanumeric with dots, hyphens, underscores, and exclamation marks",
                        regex="^[a-zA-Z0-9\\.\\-_!]+$",
                    )
                ],
            ),
        ),
    ]
