# Generated by Django 5.1.4 on 2025-12-18 20:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rtc_websockets", "0004_alter_activityevent_project_id_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE realtime_presence_status
            ALTER COLUMN organization_id TYPE uuid USING organization_id::uuid;

            ALTER TABLE realtime_activity_event
            ALTER COLUMN organization_id TYPE uuid USING organization_id::uuid;

            ALTER TABLE realtime_message
            ALTER COLUMN scope_id TYPE uuid USING scope_id::text::uuid;
            """,
            reverse_sql="""
            ALTER TABLE realtime_presence_status
            ALTER COLUMN organization_id TYPE integer USING organization_id::integer;

            ALTER TABLE realtime_activity_event
            ALTER COLUMN organization_id TYPE integer USING organization_id::integer;

            ALTER TABLE realtime_message
            ALTER COLUMN scope_id TYPE integer USING scope_id::text::integer;
            """,
        )
    ]
