# Generated by Django 5.1.4 on 2026-02-10 12:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("files", "0002_add_thumbnail_path"),
        ("projects", "0015_project_sport"),
        ("workflows", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                            ("youtube", "YouTube"),
                            ("stories", "Stories"),
                        ],
                        help_text="Target platform",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Export configuration name (e.g., 'Feed Square', 'Reels')",
                        max_length=100,
                    ),
                ),
                (
                    "aspect_ratio",
                    models.CharField(
                        help_text="Aspect ratio (e.g., '1:1', '9:16', '16:9')", max_length=10
                    ),
                ),
                (
                    "max_duration_seconds",
                    models.IntegerField(
                        blank=True, help_text="Maximum video duration in seconds", null=True
                    ),
                ),
                (
                    "max_file_size_mb",
                    models.IntegerField(
                        blank=True, help_text="Maximum file size in megabytes", null=True
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        help_text="Target resolution (e.g., '1080x1080', '1080x1920')",
                        max_length=20,
                    ),
                ),
                (
                    "crop_strategy",
                    models.CharField(
                        choices=[
                            ("crop", "Crop to fit"),
                            ("letterbox", "Add letterbox"),
                            ("fit", "Scale to fit"),
                        ],
                        default="crop",
                        help_text="How to handle aspect ratio conversion",
                        max_length=20,
                    ),
                ),
                (
                    "recommended",
                    models.BooleanField(
                        default=False, help_text="Recommended export for this platform"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Available for use")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Platform Export",
                "verbose_name_plural": "Platform Exports",
                "db_table": "video_platform_exports",
                "ordering": ["platform", "name"],
            },
        ),
        migrations.CreateModel(
            name="VideoPreset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique preset name (e.g., '1080p_standard')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Human-readable description of this preset"
                    ),
                ),
                (
                    "output_format",
                    models.CharField(
                        choices=[("mp4", "MP4"), ("webm", "WebM"), ("hls", "HLS")],
                        help_text="Output video format",
                        max_length=10,
                    ),
                ),
                (
                    "video_codec",
                    models.CharField(
                        blank=True,
                        help_text="FFmpeg video codec (e.g., 'libx264', 'libvpx-vp9')",
                        max_length=50,
                    ),
                ),
                (
                    "audio_codec",
                    models.CharField(
                        blank=True,
                        help_text="FFmpeg audio codec (e.g., 'aac', 'libopus')",
                        max_length=50,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        help_text="Target resolution (e.g., '1920x1080', '1280x720')",
                        max_length=20,
                    ),
                ),
                (
                    "bitrate_video",
                    models.CharField(
                        blank=True, help_text="Video bitrate (e.g., '5M', '2M')", max_length=20
                    ),
                ),
                (
                    "bitrate_audio",
                    models.CharField(
                        blank=True, help_text="Audio bitrate (e.g., '128k', '192k')", max_length=20
                    ),
                ),
                (
                    "framerate",
                    models.IntegerField(
                        blank=True, help_text="Target framerate (e.g., 30, 60)", null=True
                    ),
                ),
                (
                    "crf",
                    models.IntegerField(
                        blank=True,
                        help_text="Constant Rate Factor quality (0-51, lower is better)",
                        null=True,
                    ),
                ),
                (
                    "extra_params",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional FFmpeg parameters as JSON"
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="System preset (read-only, cannot be modified)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Video Preset",
                "verbose_name_plural": "Video Presets",
                "db_table": "video_presets",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VideoJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("transcode", "Transcode"),
                            ("thumbnail", "Thumbnail"),
                            ("compose", "Compose"),
                        ],
                        help_text="Type of video processing job",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        help_text="Current job status",
                        max_length=20,
                    ),
                ),
                (
                    "progress_percent",
                    models.IntegerField(default=0, help_text="Processing progress (0-100)"),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, help_text="Job-specific configuration as JSON"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Output metadata (duration, resolution, etc.)",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error details if job failed"),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, help_text="Error code for categorization", max_length=50
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, help_text="Number of retry attempts"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When processing started", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When processing completed", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this job",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "output_file",
                    models.ForeignKey(
                        blank=True,
                        help_text="Output video file",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_jobs_as_output",
                        to="files.fileasset",
                    ),
                ),
                (
                    "platform_export",
                    models.ForeignKey(
                        blank=True,
                        help_text="Platform-specific export configuration",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="video.platformexport",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this job belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_jobs",
                        to="projects.project",
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        help_text="Input video file",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="video_jobs_as_source",
                        to="files.fileasset",
                    ),
                ),
                (
                    "workflow_instance",
                    models.ForeignKey(
                        blank=True,
                        help_text="Approval workflow instance",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_jobs",
                        to="workflows.workflowinstance",
                    ),
                ),
                (
                    "preset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Encoding preset to use",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="video.videopreset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Job",
                "verbose_name_plural": "Video Jobs",
                "db_table": "video_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoOverlay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "overlay_type",
                    models.CharField(
                        choices=[
                            ("logo", "Logo"),
                            ("watermark", "Watermark"),
                            ("text", "Text"),
                            ("intro", "Intro"),
                            ("outro", "Outro"),
                        ],
                        help_text="Type of overlay",
                        max_length=20,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("top_left", "Top Left"),
                            ("top_center", "Top Center"),
                            ("top_right", "Top Right"),
                            ("center", "Center"),
                            ("bottom_left", "Bottom Left"),
                            ("bottom_center", "Bottom Center"),
                            ("bottom_right", "Bottom Right"),
                            ("custom", "Custom"),
                        ],
                        help_text="Position preset or custom",
                        max_length=20,
                    ),
                ),
                (
                    "position_x",
                    models.IntegerField(
                        blank=True, help_text="Custom X coordinate (pixels from left)", null=True
                    ),
                ),
                (
                    "position_y",
                    models.IntegerField(
                        blank=True, help_text="Custom Y coordinate (pixels from top)", null=True
                    ),
                ),
                (
                    "padding_percent",
                    models.IntegerField(
                        default=5, help_text="Edge padding as percentage of video width"
                    ),
                ),
                ("opacity", models.FloatField(default=1.0, help_text="Opacity (0.0-1.0)")),
                (
                    "start_time",
                    models.FloatField(
                        blank=True,
                        help_text="Start time in seconds (null = from beginning)",
                        null=True,
                    ),
                ),
                (
                    "end_time",
                    models.FloatField(
                        blank=True, help_text="End time in seconds (null = until end)", null=True
                    ),
                ),
                (
                    "z_index",
                    models.IntegerField(default=0, help_text="Layer order (higher values on top)"),
                ),
                (
                    "content",
                    models.JSONField(
                        blank=True, default=dict, help_text="Type-specific configuration as JSON"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset_file",
                    models.ForeignKey(
                        blank=True,
                        help_text="Asset file (logo, intro video, etc.)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_overlays",
                        to="files.fileasset",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        help_text="Video job this overlay belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overlays",
                        to="video.videojob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Overlay",
                "verbose_name_plural": "Video Overlays",
                "db_table": "video_overlays",
                "ordering": ["z_index", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="platformexport",
            name="preset",
            field=models.ForeignKey(
                help_text="Encoding preset to use",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="platform_exports",
                to="video.videopreset",
            ),
        ),
        migrations.AddIndex(
            model_name="videojob",
            index=models.Index(fields=["project", "status"], name="video_jobs_project_06f5c0_idx"),
        ),
        migrations.AddIndex(
            model_name="videojob",
            index=models.Index(
                fields=["created_by", "created_at"], name="video_jobs_created_44734d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videojob",
            index=models.Index(fields=["job_type", "status"], name="video_jobs_job_typ_666177_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="platformexport",
            unique_together={("platform", "name")},
        ),
    ]
