# Generated by Django 5.1.4 on 2026-02-10 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="videojob",
            old_name="source_file",
            new_name="input_file",
        ),
    ]
