# Generated by Django 5.1.4 on 2026-02-11 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0002_add_thumbnail_path"),
        ("video", "0002_rename_source_to_input"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videojob",
            name="input_file",
            field=models.ForeignKey(
                blank=True,
                help_text="Input video file (optional for lineup jobs)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="video_jobs_as_source",
                to="files.fileasset",
            ),
        ),
        migrations.AlterField(
            model_name="videojob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("transcode", "Transcode"),
                    ("thumbnail", "Thumbnail"),
                    ("compose", "Compose"),
                    ("lineup", "Lineup"),
                ],
                help_text="Type of video processing job",
                max_length=20,
            ),
        ),
    ]
