# Generated by Django 5.1.4 on 2026-02-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0003_add_lineup_job_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videojob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("transcode", "Transcode"),
                    ("thumbnail", "Thumbnail"),
                    ("compose", "Compose"),
                    ("lineup", "Lineup"),
                    ("goal_celebration", "Goal Celebration"),
                    ("match_intro", "Match Intro"),
                ],
                help_text="Type of video processing job",
                max_length=20,
            ),
        ),
    ]
