/**
 * useMatchDetailData — thin orchestrator (composition-of-hooks pattern)
 *
 * Sub-hooks (each < 500 lines):
 *   useMatchFormState      — all useState + provider context + sync effects
 *   useMatchDataFetching   — competition/match/opponent, roster, squad, lineup sync
 *   useMatchContentMedia   — media items, content items, templates, toasts
 *   useMatchDerived        — paths, activeTab, walletOptions, display values
 *   useMatchActions        — mutations, navigation, participation CRUD
 */

export type { MatchDetailDataReturn } from './matchDetailTypes';
export type {
  Participation, ActivityEvent, OrgMember, SeasonSquadParticipation,
  ProjectMember, MatchDetail, ContentItemStatus, ContentItem,
} from './matchDetailTypes';

import type { MatchDetailDataReturn } from './matchDetailTypes';
import { useMatchFormState } from './useMatchFormState';
import { useMatchDataFetching } from './useMatchDataFetching';
import { useMatchContentMedia } from './useMatchContentMedia';
import { useMatchDerived } from './useMatchDerived';
import { useMatchActions } from './useMatchActions';

export function useMatchDetailData(): MatchDetailDataReturn {
  /* ── 1. Form state (all useState, context, router) ── */
  const formState = useMatchFormState();

  /* ── 2. Data fetching (competition, match, roster, squad, lineup sync) ── */
  useMatchDataFetching({
    apiBaseUrl: formState.apiBaseUrl,
    resolvedSeasonId: formState.resolvedSeasonId,
    providerCompetitions: formState.providerCompetitions,
    effectiveCompetitionIdVal: formState.effectiveCompetitionIdVal,
    effectiveMatchIdVal: formState.effectiveMatchIdVal,
    seasonsBasePath: formState.seasonsBasePath,
    seasonKeyOrId: formState.seasonKeyOrId,
    orgSlugOrId: formState.orgSlugOrId,
    club: formState.club,
    match: formState.match,
    navigate: formState.navigate,
    location: formState.location,
    setLoading: formState.setLoading,
    setError: formState.setError,
    setCompetition: formState.setCompetition,
    setResolvedCompetitionUuid: formState.setResolvedCompetitionUuid,
    setMatch: formState.setMatch,
    setOpponentClub: formState.setOpponentClub,
    setRosterLoading: formState.setRosterLoading,
    setRosterError: formState.setRosterError,
    setTeamProjectMembers: formState.setTeamProjectMembers,
    setOrgMembersAll: formState.setOrgMembersAll,
    setEligibleMembers: formState.setEligibleMembers,
    setClubProjectMembers: formState.setClubProjectMembers,
    setLineupSquadLoading: formState.setLineupSquadLoading,
    setLineupSquad: formState.setLineupSquad,
    setLineupFormation: formState.setLineupFormation,
    setLineupSlots: formState.setLineupSlots,
    setLineupBenchStatus: formState.setLineupBenchStatus,
  });

  /* ── 3. Content & media (media items, templates, flags, toasts) ── */
  const contentMedia = useMatchContentMedia({
    apiBaseUrl: formState.apiBaseUrl,
    match: formState.match,
    org: formState.org,
    club: formState.club,
    competition: formState.competition,
    setMatchMedia: formState.setMatchMedia,
    setMatchMediaLoading: formState.setMatchMediaLoading,
    setContentItems: formState.setContentItems,
    setContentItemsLoading: formState.setContentItemsLoading,
    setTemplateFlagMap: formState.setTemplateFlagMap,
    setTemplateFlagsLoading: formState.setTemplateFlagsLoading,
    setAvailableTemplates: formState.setAvailableTemplates,
    setTemplatesLoading: formState.setTemplatesLoading,
    setToasts: formState.setToasts,
    templateFlagMap: formState.templateFlagMap,
    matchMedia: formState.matchMedia,
    contentItems: formState.contentItems,
  });

  /* ── 4. Derived values (paths, tabs, display, participations) ── */
  const derived = useMatchDerived({
    effectiveCompetitionIdVal: formState.effectiveCompetitionIdVal,
    effectiveMatchIdVal: formState.effectiveMatchIdVal,
    seasonKeyOrId: formState.seasonKeyOrId,
    seasonsBasePath: formState.seasonsBasePath,
    location: formState.location,
    isPlayer: formState.isPlayer,
    isSupporter: formState.isSupporter,
    project: formState.project,
    match: formState.match,
    club: formState.club,
    opponentClub: formState.opponentClub,
    opponentClubBrand: formState.opponentClubBrand,
    brandLogoUrl: formState.brandLogoUrl,
  });

  /* ── 5. Actions (mutations, navigation, participation CRUD) ── */
  const actions = useMatchActions({
    apiBaseUrl: formState.apiBaseUrl,
    match: formState.match,
    setMatch: formState.setMatch,
    org: formState.org,
    project: formState.project,
    navigate: formState.navigate,
    location: formState.location,
    competitionBasePath: derived.competitionBasePath,
    homeTeamName: derived.homeTeamName,
    awayTeamName: derived.awayTeamName,
    lineupFormation: formState.lineupFormation,
    lineupSlots: formState.lineupSlots,
    lineupBenchStatus: formState.lineupBenchStatus,
    setLineupSaving: formState.setLineupSaving,
    setLineupSaveSuccess: formState.setLineupSaveSuccess,
    fetchMatchMedia: contentMedia.fetchMatchMedia,
    refreshMatchMedia: contentMedia.refreshMatchMedia,
    fetchContentItems: contentMedia.fetchContentItems,
    setSelectedTemplate: formState.setSelectedTemplate,
    setSelectedContentTypeLabel: formState.setSelectedContentTypeLabel,
    setIsContentModalOpen: formState.setIsContentModalOpen,
    setSelectedContentItem: formState.setSelectedContentItem,
    setIsContentPreviewOpen: formState.setIsContentPreviewOpen,
  });

  /* ── Return all fields (matches MatchDetailDataReturn interface) ── */
  return {
    navigate: formState.navigate,
    location: formState.location,
    user: formState.user,
    org: formState.org,
    project: formState.project,
    club: formState.club,
    season: formState.season,
    resolvedSeasonId: formState.resolvedSeasonId,
    providerLoading: formState.providerLoading,
    isPlayer: formState.isPlayer,
    isSupporter: formState.isSupporter,
    apiBaseUrl: formState.apiBaseUrl,
    orgSlugOrId: formState.orgSlugOrId,
    clubSlugOrId: formState.clubSlugOrId,
    seasonsBasePath: formState.seasonsBasePath,
    brandLogoUrl: formState.brandLogoUrl,
    effectiveCompetitionId: formState.effectiveCompetitionIdVal,
    effectiveMatchId: formState.effectiveMatchIdVal,
    opponentClub: formState.opponentClub,
    opponentClubBrand: formState.opponentClubBrand,
    competition: formState.competition,
    match: formState.match,
    setMatch: formState.setMatch,
    resolvedCompetitionUuid: formState.resolvedCompetitionUuid,
    loading: formState.loading,
    error: formState.error,
    activatingContext: formState.activatingContext,
    setActivatingContext: formState.setActivatingContext,
    activeContext: formState.activeContext,
    setActiveContextState: formState.setActiveContextState,
    isCreateTxnModalOpen: formState.isCreateTxnModalOpen,
    setIsCreateTxnModalOpen: formState.setIsCreateTxnModalOpen,
    isMatchDetailModalOpen: formState.isMatchDetailModalOpen,
    setIsMatchDetailModalOpen: formState.setIsMatchDetailModalOpen,
    isMatchEditModalOpen: formState.isMatchEditModalOpen,
    setIsMatchEditModalOpen: formState.setIsMatchEditModalOpen,
    isContentModalOpen: formState.isContentModalOpen,
    selectedTemplate: formState.selectedTemplate,
    selectedContentTypeLabel: formState.selectedContentTypeLabel,
    openContentModal: actions.openContentModal,
    closeContentModal: actions.closeContentModal,
    contentItems: formState.contentItems,
    contentItemsLoading: formState.contentItemsLoading,
    selectedContentItem: formState.selectedContentItem,
    isContentPreviewOpen: formState.isContentPreviewOpen,
    openContentPreview: actions.openContentPreview,
    closeContentPreview: actions.closeContentPreview,
    fetchContentItems: contentMedia.fetchContentItems,
    getContentItemForSubtype: contentMedia.getContentItemForSubtype,
    matchMedia: formState.matchMedia,
    matchMediaLoading: formState.matchMediaLoading,
    mediaBySubtype: contentMedia.mediaBySubtype,
    getLatestMediaForSubtype: contentMedia.getLatestMediaForSubtype,
    getMediaHistoryForSubtype: contentMedia.getMediaHistoryForSubtype,
    refreshMatchMedia: contentMedia.refreshMatchMedia,
    handleDeleteMediaItem: actions.handleDeleteMediaItem,
    handleRestoreMediaItem: actions.handleRestoreMediaItem,
    savedAssetPreview: formState.savedAssetPreview,
    setSavedAssetPreview: formState.setSavedAssetPreview,
    availableTemplates: formState.availableTemplates,
    templatesLoading: formState.templatesLoading,
    toasts: formState.toasts,
    dismissToast: contentMedia.dismissToast,
    handleContentGenerated: contentMedia.handleContentGenerated,
    matchWalletOptions: derived.matchWalletOptions,
    eligibleMembers: formState.eligibleMembers,
    orgMembersAll: formState.orgMembersAll,
    teamProjectMembers: formState.teamProjectMembers,
    clubProjectMembers: formState.clubProjectMembers,
    rosterLoading: formState.rosterLoading,
    rosterError: formState.rosterError,
    addHomeMemberId: formState.addHomeMemberId,
    setAddHomeMemberId: formState.setAddHomeMemberId,
    addAwayMemberId: formState.addAwayMemberId,
    setAddAwayMemberId: formState.setAddAwayMemberId,
    lineupBulkSubmitting: formState.lineupBulkSubmitting,
    setLineupBulkSubmitting: formState.setLineupBulkSubmitting,
    lineupEligibleSearchHome: formState.lineupEligibleSearchHome,
    setLineupEligibleSearchHome: formState.setLineupEligibleSearchHome,
    lineupEligibleSearchAway: formState.lineupEligibleSearchAway,
    setLineupEligibleSearchAway: formState.setLineupEligibleSearchAway,
    selectedEligibleLineupMemberIdsHome: formState.selectedEligibleLineupMemberIdsHome,
    setSelectedEligibleLineupMemberIdsHome: formState.setSelectedEligibleLineupMemberIdsHome,
    selectedEligibleLineupMemberIdsAway: formState.selectedEligibleLineupMemberIdsAway,
    setSelectedEligibleLineupMemberIdsAway: formState.setSelectedEligibleLineupMemberIdsAway,
    selectedLineupParticipationIdsHome: formState.selectedLineupParticipationIdsHome,
    setSelectedLineupParticipationIdsHome: formState.setSelectedLineupParticipationIdsHome,
    selectedLineupParticipationIdsAway: formState.selectedLineupParticipationIdsAway,
    setSelectedLineupParticipationIdsAway: formState.setSelectedLineupParticipationIdsAway,
    lineupFormation: formState.lineupFormation,
    setLineupFormation: formState.setLineupFormation,
    lineupSlots: formState.lineupSlots,
    setLineupSlots: formState.setLineupSlots,
    lineupSquad: formState.lineupSquad,
    lineupSquadLoading: formState.lineupSquadLoading,
    lineupBenchStatus: formState.lineupBenchStatus,
    setLineupBenchStatus: formState.setLineupBenchStatus,
    lineupSaving: formState.lineupSaving,
    lineupSaveSuccess: formState.lineupSaveSuccess,
    saveLineup: actions.saveLineup,
    competitionBasePath: derived.competitionBasePath,
    matchBasePath: derived.matchBasePath,
    activeTab: derived.activeTab,
    navigateToTab: actions.navigateToTab,
    date: derived.date,
    status: derived.status,
    isHome: derived.isHome,
    ownTeamName: derived.ownTeamName,
    opponentName: derived.opponentName,
    homeTeamName: derived.homeTeamName,
    awayTeamName: derived.awayTeamName,
    ownLogoUrl: derived.ownLogoUrl,
    opponentLogoUrl: derived.opponentLogoUrl,
    homeLogoUrl: derived.homeLogoUrl,
    awayLogoUrl: derived.awayLogoUrl,
    scoreDisplay: derived.scoreDisplay,
    homeParticipations: derived.homeParticipations,
    awayParticipations: derived.awayParticipations,
    matchEvents: derived.matchEvents,
    saveMatchEdits: actions.saveMatchEdits,
    handleDeleteMatch: actions.handleDeleteMatch,
    createParticipation: actions.createParticipation,
    updateParticipation: actions.updateParticipation,
    deleteParticipation: actions.deleteParticipation,
    bulkCreateParticipations: actions.bulkCreateParticipations,
    bulkDeleteParticipations: actions.bulkDeleteParticipations,
    refreshMatch: actions.refreshMatch,
    pendingClubSlugResolve: formState.pendingClubSlugResolve,
    clubSlugRedirectTarget: formState.clubSlugRedirectTarget,
  };
}
