# Generated by Django 5.1.4 on 2025-11-24 16:51

from django.db import migrations


def create_default_groups(apps, schema_editor):
    """Create default groups and assign permissions to admin group."""
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    # Create groups first
    superadmin_group, _ = Group.objects.get_or_create(name="superadmin")
    admin_group, _ = Group.objects.get_or_create(name="admin")
    user_group, _ = Group.objects.get_or_create(name="user")

    # Get or create User content type (it might not exist yet during migrations)
    user_ct, _ = ContentType.objects.get_or_create(
        app_label="accounts",
        model="user",
    )

    # Try to assign permissions to admin group (they might not exist yet)
    try:
        add_perm = Permission.objects.get(codename="add_user", content_type=user_ct)
        change_perm = Permission.objects.get(codename="change_user", content_type=user_ct)
        view_perm = Permission.objects.get(codename="view_user", content_type=user_ct)
        admin_group.permissions.add(add_perm, change_perm, view_perm)
    except Permission.DoesNotExist:
        # Permissions will be created by Django's post_migrate signal
        pass


def reverse_create_groups(apps, schema_editor):
    """Remove default groups on migration rollback."""
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["superadmin", "admin", "user"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("contenttypes", "__latest__"),
    ]

    operations = [
        migrations.RunPython(create_default_groups, reverse_create_groups),
    ]
