# Generated by Django 5.1.4 on 2026-02-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_user_active_context_membership"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="useractivecontext",
            new_name="accounts_us_user_id_42c51f_idx",
            old_name="accounts_us_user_id_0f095c_idx",
        ),
        migrations.RenameIndex(
            model_name="useractivecontext",
            new_name="accounts_us_organis_2af13d_idx",
            old_name="accounts_us_organis_1b9466_idx",
        ),
        migrations.RenameIndex(
            model_name="useractivecontext",
            new_name="accounts_us_club_id_544200_idx",
            old_name="accounts_us_club_id_7e5b8d_idx",
        ),
        migrations.RenameIndex(
            model_name="useractivecontext",
            new_name="accounts_us_team_id_cf0a3e_idx",
            old_name="accounts_us_team_id_1a7c20_idx",
        ),
        migrations.RenameIndex(
            model_name="useractivecontext",
            new_name="accounts_us_members_9f4cf7_idx",
            old_name="accounts_us_membersh_8b3f70_idx",
        ),
        migrations.AlterField(
            model_name="useractivecontext",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
