# Generated by Django 5.1.4 on 2026-02-06 11:31

from django.db import migrations
import unicodedata


def merge_duplicate_emails(apps, schema_editor):
    """
    Merge duplicate user accounts with the same normalized email.

    Strategy:
    1. Find all users with accent variants of the same email (e.g., martínez vs martinez)
    2. Keep the oldest account (lowest ID) as the canonical one
    3. Update all foreign keys pointing to duplicates to point to the canonical account
    4. Delete duplicate accounts
    """
    User = apps.get_model("accounts", "User")
    db_alias = schema_editor.connection.alias

    # Get all users
    all_users = User.objects.using(db_alias).all().order_by("id")

    # Group users by normalized email
    email_groups = {}
    for user in all_users:
        if not user.email:
            continue

        # Normalize: remove accents, lowercase, strip
        norm_email = (
            unicodedata.normalize("NFKD", user.email.lower().strip())
            .encode("ASCII", "ignore")
            .decode("utf-8")
        )

        if norm_email not in email_groups:
            email_groups[norm_email] = []
        email_groups[norm_email].append(user)

    # Process duplicates
    merged_count = 0
    for norm_email, users in email_groups.items():
        if len(users) <= 1:
            continue  # No duplicates

        # Keep the first (oldest) user
        canonical_user = users[0]
        duplicates = users[1:]

        print(f"Merging {len(duplicates)} duplicate(s) for {canonical_user.email}:")

        for dup in duplicates:
            print(
                f"  - Merging {dup.email} (ID {dup.id}) into {canonical_user.email} (ID {canonical_user.id})"
            )

            # Update foreign keys
            # ProjectMembership
            ProjectMembership = apps.get_model("projects", "ProjectMembership")
            memberships = ProjectMembership.objects.using(db_alias).filter(user=dup)
            for m in memberships:
                # Check if canonical already has membership in this project
                # Note: unique constraint is on (project, user) for active memberships
                existing = (
                    ProjectMembership.objects.using(db_alias)
                    .filter(user=canonical_user, project=m.project)
                    .exists()
                )

                if existing:
                    # Duplicate membership exists, just delete this one
                    print(f"    Skipping duplicate membership: project={m.project_id}")
                    m.delete()
                else:
                    # Transfer membership to canonical user
                    m.user = canonical_user
                    m.save(update_fields=["user"])

            # Update Search Entries
            SearchEntry = apps.get_model("search", "SearchEntry")
            ContentType = apps.get_model("contenttypes", "ContentType")
            user_ct = ContentType.objects.get_for_model(User)
            SearchEntry.objects.using(db_alias).filter(
                content_type=user_ct, object_id=dup.id
            ).delete()

            # Delete the duplicate user
            dup.delete()
            merged_count += 1

    print(f"\nMerged {merged_count} duplicate user account(s)")


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0006_rename_accounts_us_user_id_0f095c_idx_accounts_us_user_id_42c51f_idx_and_more",
        ),
        ("projects", "0015_project_sport"),  # ProjectMembership available
        ("search", "0001_enable_pg_trgm"),  # SearchEntry available
    ]

    operations = [
        migrations.RunPython(merge_duplicate_emails, reverse_code=migrations.RunPython.noop),
    ]
