# Generated by Django 5.1.4 on 2025-11-25 18:54
"""
Initial schema for hierarchical access control system.

Models:
- Permission: Specific capabilities (e.g., projects.delete)
- Role: Named permission collections (e.g., Organization Admin)
- RoleAssignment: User-to-role links at specific scopes (global/org/project)

Indexes optimize queries:
- role_name_scope_idx: Fast role lookup by name+scope
- roleassign_user_idx: Fast "get roles for user" queries
- roleassign_scope_org_idx, roleassign_scope_proj_idx: Fast scope-filtered queries
"""

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organisations", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this permission",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        help_text="Permission string (format: resource.action, e.g., 'projects.delete')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        help_text="Resource category (e.g., 'project', 'organisation', 'account')",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable explanation of what this permission allows",
                    ),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this permission triggers audit logging (e.g., delete, invite)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "db_table": "permissions_permission",
                "ordering": ["resource_type", "permission"],
                "indexes": [
                    models.Index(fields=["permission"], name="perm_string_idx"),
                    models.Index(fields=["resource_type"], name="perm_resource_idx"),
                    models.Index(fields=["is_sensitive"], name="perm_sensitive_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this role",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this role (e.g., 'Organization Admin')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable explanation of role purpose and permissions",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("organization", "Organization"),
                            ("project", "Project"),
                        ],
                        help_text="Scope level where this role can be assigned",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Permissions granted by this role",
                        related_name="roles",
                        to="permissions.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "db_table": "permissions_role",
                "ordering": ["scope", "name"],
            },
        ),
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this role assignment",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("organization", "Organization"),
                            ("project", "Project"),
                        ],
                        help_text="Scope level of this assignment (global/organization/project)",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this assignment was created"
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this assignment (audit trail)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        help_text="Role being assigned to user",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="assignments",
                        to="permissions.role",
                    ),
                ),
                (
                    "target_organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target organization (required if scope=organization)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "target_project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target project (required if scope=project)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User receiving this role",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Assignment",
                "verbose_name_plural": "Role Assignments",
                "db_table": "permissions_roleassignment",
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["name", "scope"], name="role_name_scope_idx"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["scope"], name="role_scope_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("name", "scope")},
        ),
        migrations.AddIndex(
            model_name="roleassignment",
            index=models.Index(fields=["user"], name="roleassign_user_idx"),
        ),
        migrations.AddIndex(
            model_name="roleassignment",
            index=models.Index(
                fields=["scope", "target_organization"], name="roleassign_scope_org_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roleassignment",
            index=models.Index(
                fields=["scope", "target_project"], name="roleassign_scope_proj_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roleassignment",
            index=models.Index(fields=["assigned_at"], name="roleassign_date_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="roleassignment",
            unique_together={("user", "scope", "target_organization", "target_project")},
        ),
    ]
