# Generated by Django 5.1.4 on 2026-02-09 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("projects", "0015_project_sport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("version", models.CharField(max_length=50)),
                (
                    "definition",
                    models.JSONField(help_text="Workflow structure: states, transitions, hooks"),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "workflow_templates",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "-created_at"], name="workflow_te_is_acti_4d969f_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "workflow_snapshot",
                    models.JSONField(help_text="Immutable copy of workflow definition at creation"),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("current_state", models.CharField(db_index=True, max_length=100)),
                (
                    "context",
                    models.JSONField(default=dict, help_text="Arbitrary workflow data (max 64KB)"),
                ),
                ("version", models.IntegerField(default=0, help_text="Optimistic locking")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_instances",
                        to="projects.project",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="workflows.workflowtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_instances",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectPermissionOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("action_name", models.CharField(db_index=True, max_length=100)),
                (
                    "required_roles",
                    models.JSONField(
                        default=list,
                        help_text="Array of membership role names (e.g., ['admin', 'coach'])",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_permissions",
                        to="projects.project",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_overrides",
                        to="workflows.workflowtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "project_permission_overrides",
            },
        ),
        migrations.CreateModel(
            name="TransitionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("from_state", models.CharField(db_index=True, max_length=100)),
                ("to_state", models.CharField(db_index=True, max_length=100)),
                ("action", models.CharField(db_index=True, max_length=100)),
                ("comment", models.TextField(blank=True)),
                (
                    "task_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Celery task ID for async hooks",
                        null=True,
                    ),
                ),
                (
                    "context_snapshot",
                    models.JSONField(
                        default=dict, help_text="Copy of instance.context at transition time"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="workflows.workflowinstance",
                    ),
                ),
            ],
            options={
                "db_table": "transition_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["instance", "-created_at"], name="transition__instanc_92fb9e_idx"
                    ),
                    models.Index(
                        fields=["from_state", "to_state"], name="transition__from_st_bede12_idx"
                    ),
                    models.Index(fields=["-created_at"], name="transition__created_59f765_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(
                fields=["project", "current_state"], name="workflow_in_project_76eb5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(
                fields=["content_type", "object_id"], name="workflow_in_content_a676aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(
                fields=["workflow", "-created_at"], name="workflow_in_workflo_74f789_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectpermissionoverride",
            index=models.Index(
                fields=["project", "workflow"], name="project_per_project_726167_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectpermissionoverride",
            unique_together={("project", "workflow", "action_name")},
        ),
    ]
