# Generated by Django 5.1.4 on 2026-02-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowinstance",
            name="object_id",
            field=models.CharField(max_length=36),
        ),
    ]
