"""Redis cache layer with pub/sub invalidation."""

from typing import Any, Optional, Union
from uuid import UUID

from django.conf import settings
from django.core.cache import cache

# Cache configuration
CACHE_ENABLED = getattr(settings, "SETTINGS_CACHE_ENABLED", True)
CACHE_TTL = getattr(settings, "SETTINGS_CACHE_TTL", 300)  # 5 minutes default
CACHE_PREFIX = getattr(settings, "SETTINGS_CACHE_PREFIX", "settings:")
PUBSUB_CHANNEL = f"{CACHE_PREFIX}invalidate"


def generate_cache_key(
    item_type: str,
    key: str,
    scope: str,
    scope_id: Optional[Union[UUID, str]] = None,
) -> str:
    """
    Generate a cache key for a setting or feature flag.

    Args:
        item_type: 'flag' or 'setting'
        key: Setting/flag key
        scope: 'global', 'organisation', or 'project'
        scope_id: UUID of organisation or project (None for global)

    Returns:
        Cache key string in format: settings:{type}:{scope}:{id}:{key}

    Examples:
        >>> generate_cache_key('flag', 'maintenance_mode', 'global')
        'settings:flag:global:none:maintenance_mode'
        >>> generate_cache_key('setting', 'max_upload_size', 'organisation', org_id)
        'settings:setting:organisation:123e4567-e89b-12d3-a456-426614174000:max_upload_size'
    """
    scope_id_str = str(scope_id) if scope_id else "none"
    return f"{CACHE_PREFIX}{item_type}:{scope}:{scope_id_str}:{key}"


def get_cached_value(cache_key: str) -> Optional[Any]:
    """
    Get a value from cache with graceful degradation.

    Args:
        cache_key: Cache key generated by generate_cache_key()

    Returns:
        Cached value or None if not found or cache unavailable
    """
    if not CACHE_ENABLED:
        return None

    try:
        return cache.get(cache_key)
    except Exception:
        # Graceful degradation: if Redis unavailable, return None (database fallback)
        return None


def set_cached_value(cache_key: str, value: Any, ttl: Optional[int] = None) -> bool:
    """
    Set a value in cache with TTL.

    Args:
        cache_key: Cache key generated by generate_cache_key()
        value: Value to cache
        ttl: Time-to-live in seconds (default: CACHE_TTL)

    Returns:
        True if cached successfully, False if cache unavailable
    """
    if not CACHE_ENABLED:
        return False

    try:
        cache.set(cache_key, value, timeout=ttl or CACHE_TTL)
        return True
    except Exception:
        # Graceful degradation: if Redis unavailable, silently fail
        return False


def invalidate_cache(cache_key: str) -> bool:
    """
    Invalidate (delete) a cache entry.

    Args:
        cache_key: Cache key to invalidate

    Returns:
        True if invalidated successfully, False if cache unavailable
    """
    if not CACHE_ENABLED:
        return False

    try:
        cache.delete(cache_key)
        return True
    except Exception:
        # Graceful degradation: if Redis unavailable, silently fail
        return False


def publish_invalidation(cache_key: str) -> bool:
    """
    Publish a cache invalidation message to Redis pub/sub channel.

    This allows multiple application instances to receive invalidation
    notifications and clear their local caches when settings change.

    Args:
        cache_key: Cache key that was invalidated

    Returns:
        True if published successfully, False if Redis unavailable
    """
    if not CACHE_ENABLED:
        return False

    try:
        # Get Redis client from django-redis
        from django_redis import get_redis_connection

        redis_client = get_redis_connection("default")
        redis_client.publish(PUBSUB_CHANNEL, cache_key)
        return True
    except Exception:
        # Graceful degradation: if Redis unavailable or django-redis not installed
        return False
