/**
 * ThemeProvider component tests.
 *
 * Validates provider behavior, data attribute application, and system preference detection.
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { ThemeProvider } from '../../../src/components/ThemeProvider';
import { useTheme } from '../../../src/hooks/useTheme';
import type { ThemeStorage } from '../../../src/storage/types';

describe('ThemeProvider', () => {
  let originalDocumentElement: HTMLElement;

  beforeEach(() => {
    // Save original document element state
    originalDocumentElement = document.documentElement.cloneNode(true) as HTMLElement;
  });

  afterEach(() => {
    // Restore document element
    document.documentElement.className = originalDocumentElement.className;
    document.documentElement.removeAttribute('data-theme');
    document.documentElement.removeAttribute('data-brand');
  });

  describe('Data Attributes', () => {
    it('should apply data-theme attribute to html element', () => {
      render(
        <ThemeProvider defaultMode="light">
          <div>Content</div>
        </ThemeProvider>
      );

      expect(document.documentElement.getAttribute('data-theme')).toBe('light');
    });

    it('should apply data-brand attribute', () => {
      render(
        <ThemeProvider defaultBrand="acme">
          <div>Content</div>
        </ThemeProvider>
      );

      expect(document.documentElement.getAttribute('data-brand')).toBe('acme');
    });

    it('should update data-theme when mode changes', async () => {
      const TestComponent = () => {
        const { setTheme } = useTheme();
        return (
          <div>
            <button onClick={() => setTheme({ mode: 'dark' })}>Switch to Dark</button>
          </div>
        );
      };

      render(
        <ThemeProvider defaultMode="light">
          <TestComponent />
        </ThemeProvider>
      );

      expect(document.documentElement.getAttribute('data-theme')).toBe('light');

      const button = screen.getByRole('button', { name: /switch to dark/i });
      await userEvent.click(button);

      await waitFor(() => {
        expect(document.documentElement.getAttribute('data-theme')).toBe('dark');
      });
    });

    it('should apply theme class to html element', () => {
      render(
        <ThemeProvider defaultMode="dark">
          <div>Content</div>
        </ThemeProvider>
      );

      // Theme class is generated by vanilla-extract
      expect(document.documentElement.className).toBeTruthy();
      expect(document.documentElement.className.length).toBeGreaterThan(0);
    });
  });

  describe('System Preference', () => {
    it('should resolve system mode to light when OS prefers light', () => {
      const matchMediaMock = vi.fn().mockReturnValue({
        matches: false, // light mode
        addEventListener: vi.fn(),
        removeEventListener: vi.fn(),
        addListener: vi.fn(), // Legacy
        removeListener: vi.fn(), // Legacy
      });
      vi.stubGlobal('matchMedia', matchMediaMock);

      render(
        <ThemeProvider defaultMode="system">
          <div>Content</div>
        </ThemeProvider>
      );

      expect(document.documentElement.getAttribute('data-theme')).toBe('light');
    });

    it('should resolve system mode to dark when OS prefers dark', () => {
      const matchMediaMock = vi.fn().mockReturnValue({
        matches: true, // dark mode
        addEventListener: vi.fn(),
        removeEventListener: vi.fn(),
        addListener: vi.fn(),
        removeListener: vi.fn(),
      });
      vi.stubGlobal('matchMedia', matchMediaMock);

      render(
        <ThemeProvider defaultMode="system">
          <div>Content</div>
        </ThemeProvider>
      );

      expect(document.documentElement.getAttribute('data-theme')).toBe('dark');
    });

    it('should subscribe to system preference changes', () => {
      const addEventListener = vi.fn();
      const matchMediaMock = vi.fn().mockReturnValue({
        matches: false,
        addEventListener,
        removeEventListener: vi.fn(),
        addListener: vi.fn(),
        removeListener: vi.fn(),
      });
      vi.stubGlobal('matchMedia', matchMediaMock);

      render(
        <ThemeProvider defaultMode="system">
          <div>Content</div>
        </ThemeProvider>
      );

      expect(addEventListener).toHaveBeenCalledWith('change', expect.any(Function));
    });
  });

  describe('Storage Integration', () => {
    it('should load theme from storage on mount', async () => {
      const mockStorage: ThemeStorage = {
        getTheme: vi.fn().mockResolvedValue({ mode: 'dark', brand: 'acme' }),
        setTheme: vi.fn().mockResolvedValue(undefined),
      };

      render(
        <ThemeProvider storage={mockStorage} defaultMode="light">
          <div>Content</div>
        </ThemeProvider>
      );

      await waitFor(() => {
        expect(mockStorage.getTheme).toHaveBeenCalled();
        expect(document.documentElement.getAttribute('data-theme')).toBe('dark');
        expect(document.documentElement.getAttribute('data-brand')).toBe('acme');
      });
    });

    it('should use defaults when storage returns null', async () => {
      const mockStorage: ThemeStorage = {
        getTheme: vi.fn().mockResolvedValue(null),
        setTheme: vi.fn().mockResolvedValue(undefined),
      };

      render(
        <ThemeProvider storage={mockStorage} defaultMode="light" defaultBrand="default">
          <div>Content</div>
        </ThemeProvider>
      );

      await waitFor(() => {
        expect(mockStorage.getTheme).toHaveBeenCalled();
        expect(document.documentElement.getAttribute('data-theme')).toBe('light');
        expect(document.documentElement.getAttribute('data-brand')).toBe('default');
      });
    });
  });

  describe('Children Rendering', () => {
    it('should render children', () => {
      render(
        <ThemeProvider>
          <div data-testid="child">Child Content</div>
        </ThemeProvider>
      );

      expect(screen.getByTestId('child')).toBeInTheDocument();
      expect(screen.getByTestId('child')).toHaveTextContent('Child Content');
    });
  });
});
