# Generated by Django 5.1.4 on 2026-02-01 19:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organisations", "0004_add_sport_to_organisation"),
        ("projects", "0015_project_sport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Human-readable template name", max_length=200),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier (unique per org)", max_length=100
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0", help_text="Semantic version (e.g., 1.0.0)", max_length=20
                    ),
                ),
                (
                    "is_latest",
                    models.BooleanField(default=True, help_text="Current active version flag"),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Template purpose and usage notes"),
                ),
                (
                    "input_schema",
                    models.JSONField(help_text="JSON Schema (Draft 7) for input validation"),
                ),
                (
                    "pipeline_config",
                    models.JSONField(
                        help_text="Pipeline config: provider, model, estimated_cost, graph_id, etc."
                    ),
                ),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        blank=True, help_text="Days until output deletion (NULL=forever)", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, help_text="Soft delete flag"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this template",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_generation_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        help_text="Organisation that owns this template",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_templates",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "parent_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Previous version (for version chain)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_versions",
                        to="generative.generationtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Generation Template",
                "verbose_name_plural": "Generation Templates",
                "db_table": "generative_template",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GenerationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "template_version",
                    models.CharField(
                        editable=False,
                        help_text="Denormalized template version for quick access",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current lifecycle status",
                        max_length=20,
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        help_text="User-provided inputs (validated against template.input_schema)"
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(default=0, help_text="Number of retry attempts"),
                ),
                (
                    "error_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("transient", "Transient"),
                            ("permanent", "Permanent"),
                            ("unknown", "Unknown"),
                        ],
                        help_text="Error classification for retry logic",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, default="", help_text="Detailed error description"
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Reserved credits amount",
                        max_digits=10,
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Final API cost (settled on completion)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "transaction_id",
                    models.BigIntegerField(
                        blank=True, help_text="B11 credit transaction reference", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Retry history, provider details, token usage, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When processing started", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When processing completed (success or failure)",
                        null=True,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional project context for scoping",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_requests",
                        to="projects.project",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        help_text="User who submitted this request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="Template version used for generation",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="generative.generationtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Generation Request",
                "verbose_name_plural": "Generation Requests",
                "db_table": "generative_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GenerationOutput",
            fields=[
                (
                    "request",
                    models.OneToOneField(
                        help_text="Parent generation request",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="output",
                        serialize=False,
                        to="generative.generationrequest",
                    ),
                ),
                (
                    "output_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("text", "Text"),
                            ("json", "JSON"),
                        ],
                        help_text="Type of generated content",
                        max_length=20,
                    ),
                ),
                (
                    "file_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="B35 FileStorageRecord reference (for media outputs)",
                        null=True,
                    ),
                ),
                (
                    "text_content",
                    models.TextField(blank=True, default="", help_text="Inline text/JSON content"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Provider-specific metadata (token usage, resolution, etc.)",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Computed: created_at + template.retention_days",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Generation Output",
                "verbose_name_plural": "Generation Outputs",
                "db_table": "generative_output",
                "indexes": [models.Index(fields=["expires_at"], name="generative_out_expires_idx")],
            },
        ),
        migrations.AddIndex(
            model_name="generationtemplate",
            index=models.Index(
                fields=["organisation", "is_active", "is_latest"],
                name="generative_tpl_org_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="generationtemplate",
            index=models.Index(fields=["slug", "version"], name="generative_tpl_slug_ver_idx"),
        ),
        migrations.AddIndex(
            model_name="generationtemplate",
            index=models.Index(fields=["created_at"], name="generative_tpl_created_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="generationtemplate",
            unique_together={("organisation", "slug", "version")},
        ),
        migrations.AddIndex(
            model_name="generationrequest",
            index=models.Index(fields=["requester", "status"], name="gen_req_user_status_idx"),
        ),
        migrations.AddIndex(
            model_name="generationrequest",
            index=models.Index(fields=["project", "created_at"], name="gen_req_proj_created_idx"),
        ),
        migrations.AddIndex(
            model_name="generationrequest",
            index=models.Index(fields=["template", "status"], name="gen_req_tpl_status_idx"),
        ),
        migrations.AddIndex(
            model_name="generationrequest",
            index=models.Index(fields=["status", "created_at"], name="gen_req_status_created_idx"),
        ),
    ]
