# Generated by Django 5.1.4 on 2026-02-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generative", "0001_initial"),
    ]

    operations = [
        # Drop the old bigint column (safe - no production data yet)
        migrations.RemoveField(
            model_name="generationoutput",
            name="file_id",
        ),
        # Recreate as UUID
        migrations.AddField(
            model_name="generationoutput",
            name="file_id",
            field=models.UUIDField(
                blank=True, help_text="B22 FileAsset UUID reference (for media outputs)", null=True
            ),
        ),
    ]
