# Generated by Django 5.1.4 on 2026-02-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generative", "0002_change_file_id_to_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationtemplate",
            name="template_subtype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("profile_photo", "Profile Photo"),
                    ("legacy_photo", "Legacy Photo"),
                    ("in_tenue", "In Tenue"),
                    ("closeup", "Close-up"),
                    ("short_intro", "Short Intro"),
                    ("celebration", "Celebration"),
                    ("legacy_in_tenue", "Legacy in Tenue"),
                    ("transformation", "Then vs Now"),
                    ("season_recap", "Season Recap"),
                    ("flyer", "Match Flyer"),
                    ("lineup", "Lineup Announcement"),
                    ("walkon", "Walk-on Video"),
                    ("anthem", "Anthem Video"),
                    ("goal", "Goal Celebration"),
                    ("score_update", "Score Update"),
                    ("end_score", "Final Score"),
                    ("match_summary", "Match Summary"),
                    ("highlights", "Highlights Reel"),
                    ("custom_logo", "Logo"),
                    ("custom_tenue", "Tenue"),
                    ("custom_tenue_logo", "Tenue + Logo"),
                    ("custom_tenue_logo_sponsor", "Tenue + Logo + Sponsor"),
                ],
                db_index=True,
                help_text="Specific content format within the type",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="generationtemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("member", "Member"),
                    ("season", "Season"),
                    ("pre_match", "Pre-Match"),
                    ("during_match", "During Match"),
                    ("post_match", "Post-Match"),
                    ("custom", "Custom"),
                ],
                db_index=True,
                default="custom",
                help_text="Context where template is available (member, season, match phase)",
                max_length=20,
            ),
        ),
    ]
