# Generated by Django 5.1.4 on 2026-02-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generative", "0003_add_template_type_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generationtemplate",
            name="template_subtype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("profile_photo", "Profile Photo"),
                    ("legacy_photo", "Legacy Photo"),
                    ("in_tenue", "In Tenue"),
                    ("closeup", "Close-up"),
                    ("short_intro", "Short Intro"),
                    ("celebration", "Celebration"),
                    ("legacy_in_tenue", "Legacy in Tenue"),
                    ("transformation", "Then vs Now"),
                    ("season_recap", "Season Recap"),
                    ("flyer", "Match Flyer"),
                    ("lineup", "Lineup Video"),
                    ("lineup_flyer", "Lineup Flyer"),
                    ("walkon", "Walk-on Video"),
                    ("anthem", "Anthem Video"),
                    ("goal", "Goal Celebration"),
                    ("score_update", "Score Update"),
                    ("end_score", "Final Score"),
                    ("match_summary", "Match Summary"),
                    ("highlights", "Highlights Reel"),
                    ("custom_logo", "Logo"),
                    ("custom_tenue", "Tenue"),
                    ("custom_tenue_logo", "Tenue + Logo"),
                    ("custom_tenue_logo_sponsor", "Tenue + Logo + Sponsor"),
                ],
                db_index=True,
                help_text="Specific content format within the type",
                max_length=30,
            ),
        ),
    ]
