# Generated by Django 5.1.4 on 2026-02-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generative", "0005_generation_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationjob",
            name="approval_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending_review", "Te beoordelen"),
                    ("approved", "Goedgekeurd"),
                    ("rejected", "Afgewezen"),
                ],
                db_index=True,
                help_text="Set to pending_review when completed; approved/rejected after human review",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="generationjob",
            name="output_url",
            field=models.TextField(
                blank=True,
                default="",
                help_text="URL of the primary generated output (image/video), persisted for review UI",
            ),
        ),
        migrations.AddField(
            model_name="generationjob",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generationjob",
            name="reviewed_by_id",
            field=models.IntegerField(
                blank=True, help_text="User.id who reviewed this job", null=True
            ),
        ),
    ]
