# Generated by Django 5.1.4 on 2026-03-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generative", "0007_generationjob_output_variants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generationjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "In wachtrij"),
                    ("waiting", "Wachten"),
                    ("processing", "Wordt verwerkt"),
                    ("retrying", "Opnieuw proberen"),
                    ("completed", "Voltooid"),
                    ("failed", "Mislukt"),
                    ("cancelled", "Geannuleerd"),
                ],
                db_index=True,
                default="queued",
                max_length=20,
            ),
        ),
    ]
