# Generated by Django 5.1.4 on 2026-03-31 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generative", "0008_add_retrying_status_to_generationjob"),
        ("organisations", "0004_add_sport_to_organisation"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationtemplate",
            name="parameters_schema",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Parameter definitions: {key: {label, type, options, default}}",
            ),
        ),
        migrations.AddField(
            model_name="generationtemplate",
            name="preprocessing_config",
            field=models.JSONField(
                blank=True, default=dict, help_text="Preprocessing pipeline config per input type"
            ),
        ),
        migrations.AddField(
            model_name="generationtemplate",
            name="prompt_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Actual prompt template with {placeholder} variables",
            ),
        ),
        migrations.AlterField(
            model_name="generationtemplate",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisation that owns this template (NULL = global/default template)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generation_templates",
                to="organisations.organisation",
            ),
        ),
    ]
