# Generated by Django 5.1.4 on 2025-12-18 09:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organisations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                (
                    "storage_path",
                    models.CharField(
                        help_text="The key/path used by the storage backend to retrieve the file.",
                        max_length=1024,
                        unique=True,
                    ),
                ),
                ("file_size", models.PositiveIntegerField(help_text="Size in bytes.")),
                ("mime_type", models.CharField(max_length=100)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Whether the file is publicly accessible."
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The organization this file belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="The user who uploaded the file.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "File Asset",
                "verbose_name_plural": "File Assets",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "created_at"], name="files_filea_organiz_0f3141_idx"
                    ),
                    models.Index(fields=["uploaded_by"], name="files_filea_uploade_838354_idx"),
                    models.Index(fields=["deleted_at"], name="files_filea_deleted_425487_idx"),
                ],
            },
        ),
    ]
