# Generated by Django 5.1.4 on 2025-12-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileasset",
            name="thumbnail_path",
            field=models.CharField(
                blank=True,
                help_text="Path to the generated thumbnail image.",
                max_length=1024,
                null=True,
            ),
        ),
    ]
