# Generated by Django 5.1.4 on 2026-02-02 20:42

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medialib", "0002_mediaitemrelation"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaitem",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
