# Generated by Django 5.1.4 on 2026-02-02 20:43

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0007_add_sport_to_period"),
        ("files", "0002_add_thumbnail_path"),
        ("generative", "0002_change_file_id_to_uuid"),
        ("medialib", "0003_mediaitem_search_vector"),
        ("projects", "0015_project_sport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="mediaitem",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="medialib_it_search__106b1a_gin"
            ),
        ),
    ]
