# Generated by Django 5.1.4 on 2026-02-03 05:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0002_add_thumbnail_path"),
        ("medialib", "0004_mediaitem_medialib_it_search__106b1a_gin"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaThumbnail",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("size_label", models.CharField(max_length=20)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="files.fileasset"
                    ),
                ),
                (
                    "media_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thumbnails",
                        to="medialib.mediaitem",
                    ),
                ),
            ],
            options={
                "db_table": "medialib_thumbnails",
                "ordering": ["width"],
                "unique_together": {("media_item", "size_label")},
            },
        ),
    ]
