# Generated by GitHub Copilot on 2026-01-14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("credits", "0001_initial"),
        ("projects", "0008_remove_duplicate_memberships"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCreditsBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_balance",
                    models.IntegerField(
                        default=0,
                        help_text="Current credit balance for this project/team",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time balance was updated",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this balance record was created",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        help_text="Project (team) this balance belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_credits_balance",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Credits Balance",
                "verbose_name_plural": "Project Credits Balances",
                "ordering": ["-updated_at"],
            },
        ),
    ]
