# Generated by Django 5.1.4 on 2026-01-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credits", "0002_projectcreditsbalance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectcreditsbalance",
            name="current_balance",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Current credit balance for this project/team",
                max_digits=14,
            ),
        ),
    ]
