# Generated by Django 5.1.4 on 2026-01-16 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("credits", "0004_usercreditsbalance"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="usercreditsbalance",
            new_name="credits_use_organis_eeb74d_idx",
            old_name="credits_use_org_1f4bc8_idx",
        ),
        migrations.RenameIndex(
            model_name="usercreditsbalance",
            new_name="credits_use_user_id_d39031_idx",
            old_name="credits_use_use_5f5a61_idx",
        ),
    ]
