# Generated by Django 5.1.4 on 2026-01-04 08:44

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the metric record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the metric snapshot was recorded",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("cache_hits", "Cache Hits"),
                            ("cache_misses", "Cache Misses"),
                            ("memory_used", "Memory Used (bytes)"),
                            ("total_keys", "Total Keys"),
                        ],
                        db_index=True,
                        help_text="Type of metric being recorded",
                        max_length=50,
                    ),
                ),
                ("value", models.FloatField(help_text="Numeric value of the metric")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context (e.g., cache alias, hostname)",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Metric",
                "verbose_name_plural": "System Metrics",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["metric_type", "-timestamp"], name="observabili_metric__134298_idx"
                    ),
                    models.Index(fields=["-timestamp"], name="observabili_timesta_39690b_idx"),
                ],
            },
        ),
    ]
