/**
 * Member-focused asset templates (photos, videos, composites, action shots).
 */
import type { AssetTemplate } from './assetTemplateTypes';

export const MEMBER_TEMPLATES: AssetTemplate[] = [
  // ── Player photos ──
  {
    id: 'fullbody_in_tenue',
    name: 'Speler Fullbody',
    icon: 'shirt',
    category: 'fullbody',
    description: 'Plaats een persoon in het geselecteerde tenue (transparante achtergrond). Het tenue wordt EXACT overgenomen.',
    inputRequirements: ['person', 'reference'],
    requiredAssetTypes: [],
    outputAssetType: 'member_in_tenue',
    creditsCost: 2,
    parameters: {
      kit_type: {
        label: 'Tenue Type',
        type: 'select',
        options: [
          { value: 'home', label: 'Thuistenue' },
          { value: 'away', label: 'Uittenue' },
          { value: 'third', label: 'Derde tenue' },
          { value: 'goalkeeper', label: 'Keeperstenue' },
          { value: 'coach', label: 'Trainerspak' },
          { value: 'assistant', label: 'Assistentpak' },
          { value: 'training', label: 'Trainingstenue' },
          { value: 'legacy', label: 'Legacy Tenue' },
        ],
        default: 'home',
      },
      sleeves: {
        label: 'Mouwen',
        type: 'select',
        options: [
          { value: 'long', label: 'Lang' },
          { value: 'short', label: 'Kort' },
        ],
        default: 'long',
      },
      pose: {
        label: 'Pose',
        type: 'select',
        options: [
          { value: 'standing_front', label: 'Staand (vooraan)' },
          { value: 'standing_arms_crossed', label: 'Armen gekruist' },
          { value: 'action_running', label: 'Rennend' },
          { value: 'ball_at_feet', label: 'Bal aan voet' },
        ],
        default: 'standing_front',
      },
      role: {
        label: 'Rol',
        type: 'select',
        options: [
          { value: 'player', label: 'Speler' },
          { value: 'goalkeeper', label: 'Keeper' },
          { value: 'coach', label: 'Trainer' },
          { value: 'assistant', label: 'Assistent' },
        ],
        default: 'player',
      },
    },
  },
  {
    id: 'closeup_in_tenue',
    name: 'Speler Close-up',
    icon: 'camera',
    category: 'closeup',
    description: 'Close-up portret in het geselecteerde tenue (transparante achtergrond). Het tenue wordt EXACT overgenomen.',
    inputRequirements: ['person', 'reference'],
    requiredAssetTypes: [],
    outputAssetType: 'member_closeup',
    creditsCost: 2,
    parameters: {
      kit_type: {
        label: 'Tenue Type',
        type: 'select',
        options: [
          { value: 'home', label: 'Thuistenue' },
          { value: 'away', label: 'Uittenue' },
          { value: 'third', label: 'Derde tenue' },
          { value: 'goalkeeper', label: 'Keeperstenue' },
          { value: 'coach', label: 'Trainerspak' },
          { value: 'assistant', label: 'Assistentpak' },
          { value: 'training', label: 'Trainingstenue' },
          { value: 'legacy', label: 'Legacy Tenue' },
        ],
        default: 'home',
      },
      neck: {
        label: 'Hals',
        type: 'select',
        options: [
          { value: 'round', label: 'Ronde kraag' },
          { value: 'collar', label: 'Polo kraag' },
          { value: 'v_neck', label: 'V-hals' },
        ],
        default: 'round',
      },
      expression: {
        label: 'Uitdrukking',
        type: 'select',
        options: [
          { value: 'neutral_confident', label: 'Neutraal' },
          { value: 'smiling', label: 'Glimlachend' },
          { value: 'intense', label: 'Intens' },
        ],
        default: 'neutral_confident',
      },
    },
  },
  // ── Short Intro Videos ──
  {
    id: 'member_intro',
    name: 'Short Intro Video',
    icon: 'clapperboard',
    category: 'intro',
    description: 'Korte intro video (5-6 sec) van de speler in verschillende poses. Vereist een "Player in Tenue" als input.',
    inputRequirements: ['person'],
    requiredAssetTypes: [],
    outputAssetType: 'member_intro',
    creditsCost: 5,
    outputType: 'video',
    videoConfig: {
      durationSeconds: 6,
      aspectRatio: '9:16',
      resolution: '720p',
    },
    parameters: {
      kit_type: {
        label: 'Tenue Type',
        type: 'select',
        options: [
          { value: 'home', label: 'Thuistenue' },
          { value: 'away', label: 'Uittenue' },
          { value: 'third', label: 'Derde tenue' },
          { value: 'goalkeeper', label: 'Keeperstenue' },
        ],
        default: 'home',
      },
      style_variant: {
        label: 'Pose Stijl',
        type: 'select',
        options: [
          { value: 'arms_crossed', label: 'Armen over elkaar' },
          { value: 'hand_up', label: 'Hand omhoog' },
          { value: 'thumbs_up', label: 'Duim omhoog' },
        ],
        default: 'arms_crossed',
      },
    },
  },
  // ── Goal Celebration Videos ──
  {
    id: 'member_goal_celebration',
    name: 'Goal Celebration Video',
    icon: 'party-popper',
    category: 'celebration',
    description: 'Korte goal viering video (5-6 sec) van de speler. Vereist een "Player in Tenue" als input.',
    inputRequirements: ['person'],
    requiredAssetTypes: [],
    outputAssetType: 'member_goal_celebration',
    creditsCost: 5,
    outputType: 'video',
    videoConfig: {
      durationSeconds: 6,
      aspectRatio: '9:16',
      resolution: '720p',
    },
    parameters: {
      kit_type: {
        label: 'Tenue Type',
        type: 'select',
        options: [
          { value: 'home', label: 'Thuistenue' },
          { value: 'away', label: 'Uittenue' },
          { value: 'third', label: 'Derde tenue' },
          { value: 'goalkeeper', label: 'Keeperstenue' },
        ],
        default: 'home',
      },
      style_variant: {
        label: 'Viering Stijl',
        type: 'select',
        options: [
          { value: 'arms_wide', label: 'Armen wijd' },
          { value: 'fist_pump', label: 'Vuist omhoog' },
          { value: 'point_to_sky', label: 'Wijs naar hemel' },
          { value: 'slide', label: 'Knieën slide' },
        ],
        default: 'arms_wide',
      },
    },
  },
  // ── Then vs Now Templates ──
  {
    id: 'then_vs_now_sidebyside',
    name: 'Transformation (Naast Elkaar)',
    icon: 'users',
    category: 'then_vs_now',
    description: 'Portretvideo (6 sec): legacy-versie (links) en huidige speler (rechts) naast elkaar. Ze kijken naar elkaar en lachen.',
    inputRequirements: ['person', 'reference'],
    requiredAssetTypes: [],
    outputAssetType: 'then_vs_now_sidebyside',
    creditsCost: 5,
    outputType: 'video',
    videoConfig: {
      durationSeconds: 6,
      aspectRatio: '9:16',
      resolution: '720p',
    },
    parameters: {},
  },
  {
    id: 'then_vs_now_transformation',
    name: 'Transformation (Transformatie)',
    icon: 'arrow-right-left',
    category: 'then_vs_now',
    description: 'Portretvideo (4 sec): de speler transformeert van legacy-look naar huidige look in tenue. Magisch maar realistisch.',
    inputRequirements: ['person', 'reference'],
    requiredAssetTypes: [],
    outputAssetType: 'then_vs_now_transformation',
    creditsCost: 5,
    outputType: 'video',
    videoConfig: {
      durationSeconds: 4,
      aspectRatio: '9:16',
      resolution: '720p',
    },
    parameters: {
      style_variant: {
        label: 'Transformatie Stijl',
        type: 'select' as const,
        options: [
          { value: 'hands_on_head', label: 'Handen op hoofd' },
          { value: 'spin', label: '360° Spin' },
          { value: 'clap', label: 'Klap' },
          { value: 'jersey_pull', label: 'Shirt trekken' },
          { value: 'arms_wide', label: 'Armen wijd' },
          { value: 'fist_pump', label: 'Vuist omhoog' },
          { value: 'snap', label: 'Vingerknip' },
        ],
        default: 'hands_on_head',
      },
    },
  },
  // ── Photo Composite Templates ──
  {
    id: 'photo_composite_gemini',
    name: 'Foto Composite (Beeld)',
    icon: 'camera',
    category: 'photo_composite',
    description: 'AI-composiet: legacy en huidige speler samen op een clubachtergrond. Gemini combineert beide fullbody-afbeeldingen realistisch.',
    inputRequirements: ['person', 'reference', 'background'],
    requiredAssetTypes: [],
    outputAssetType: 'photo_composite_gemini',
    creditsCost: 3,
    outputType: 'image',
    parameters: {
      background_style: {
        label: 'Achtergrond',
        type: 'select' as const,
        options: [
          { value: 'club', label: 'Clubachtergrond' },
          { value: 'stadium', label: 'Stadion' },
          { value: 'field', label: 'Speelveld' },
        ],
        default: 'club',
      },
    },
  },
  {
    id: 'photo_composite_video',
    name: 'Foto Composite (Video)',
    icon: 'clapperboard',
    category: 'photo_composite',
    description: 'MiniMax video (6 sec): de twee spelers op het composiet-beeld kijken naar elkaar, lachen, en kijken terug naar de camera.',
    inputRequirements: ['person'],
    requiredAssetTypes: [],
    outputAssetType: 'photo_composite_video',
    creditsCost: 5,
    outputType: 'video',
    videoConfig: {
      durationSeconds: 6,
      aspectRatio: '9:16',
      resolution: '720p',
    },
    parameters: {},
  },
  // ── Walking Composite Templates ──
  {
    id: 'walking_composite_far',
    name: 'Walking Composite (Ver)',
    icon: 'footprints',
    category: 'walking_composite',
    description: 'Full-body spelers ver weg op de achtergrond (15-20m afstand). Gemini plaatst beide spelers realistisch op het veld.',
    inputRequirements: ['person', 'reference', 'background'],
    requiredAssetTypes: [],
    outputAssetType: 'walking_composite_far',
    creditsCost: 3,
    outputType: 'image',
    parameters: {
      background_style: {
        label: 'Achtergrond',
        type: 'select' as const,
        options: [
          { value: 'club', label: 'Clubachtergrond' },
          { value: 'stadium', label: 'Stadion' },
          { value: 'field', label: 'Speelveld' },
        ],
        default: 'club',
      },
    },
  },
  {
    id: 'walking_composite_near',
    name: 'Walking Composite (Dichtbij)',
    icon: 'footprints',
    category: 'walking_composite',
    description: 'Full-body spelers dichtbij op de voorgrond (3-5m afstand). Gemini plaatst beide spelers groot en prominent in beeld.',
    inputRequirements: ['person', 'reference', 'background'],
    requiredAssetTypes: [],
    outputAssetType: 'walking_composite_near',
    creditsCost: 3,
    outputType: 'image',
    parameters: {
      background_style: {
        label: 'Achtergrond',
        type: 'select' as const,
        options: [
          { value: 'club', label: 'Clubachtergrond' },
          { value: 'stadium', label: 'Stadion' },
          { value: 'field', label: 'Speelveld' },
        ],
        default: 'club',
      },
    },
  },
  {
    id: 'walking_composite_video',
    name: 'Walking Composite (Video)',
    icon: 'clapperboard',
    category: 'walking_composite',
    description: 'MiniMax video (6 sec): spelers lopen van ver naar dichtbij de camera. Gebruikt het verre beeld als eerste frame en het dichtbije beeld als laatste frame.',
    inputRequirements: ['person'],
    requiredAssetTypes: [],
    outputAssetType: 'walking_composite_video',
    creditsCost: 5,
    outputType: 'video',
    videoConfig: {
      durationSeconds: 6,
      aspectRatio: '9:16',
      resolution: '720p',
    },
    parameters: {},
  },
  // ── Action Photo Templates ──
  {
    id: 'member_action_photo',
    name: 'Actiefoto',
    icon: 'zap',
    category: 'action_photo',
    description: 'Dynamische actiefoto van de speler in tenue — dribbelen, schieten, koppen en meer.',
    inputRequirements: ['person', 'reference'],
    requiredAssetTypes: [],
    outputAssetType: 'action_photo',
    creditsCost: 2,
    parameters: {
      kit_type: {
        label: 'Tenue Type',
        type: 'select',
        options: [
          { value: 'home', label: 'Thuistenue' },
          { value: 'away', label: 'Uittenue' },
          { value: 'third', label: 'Derde tenue' },
          { value: 'goalkeeper', label: 'Keeperstenue' },
        ],
        default: 'home',
      },
      style_variant: {
        label: 'Actie Stijl',
        type: 'select',
        options: [
          { value: 'dribbling', label: 'Dribbelen' },
          { value: 'shooting', label: 'Schieten' },
          { value: 'ball_at_feet', label: 'Bal aan de voet' },
          { value: 'celebrating', label: 'Vieren' },
          { value: 'heading', label: 'Koppen' },
          { value: 'sliding_tackle', label: 'Sliding' },
          { value: 'karate_kick', label: 'Karatetrap' },
        ],
        default: 'dribbling',
      },
      sleeves: {
        label: 'Mouwen',
        type: 'select',
        options: [
          { value: 'long', label: 'Lang' },
          { value: 'short', label: 'Kort' },
        ],
        default: 'long',
      },
      role: {
        label: 'Rol',
        type: 'select',
        options: [
          { value: 'player', label: 'Speler' },
          { value: 'goalkeeper', label: 'Keeper' },
        ],
        default: 'player',
      },
      shoe_color: {
        label: 'Schoenen kleur',
        type: 'select',
        options: [
          { value: 'zwart', label: 'Zwart' },
          { value: 'wit', label: 'Wit' },
          { value: 'rood', label: 'Rood' },
          { value: 'blauw', label: 'Blauw' },
          { value: 'geel', label: 'Geel' },
          { value: 'oranje', label: 'Oranje' },
        ],
        default: 'zwart',
      },
    },
  },
];
