/**
 * Kit/outfit asset templates (tenue, legacy, keeper, tracksuit, coach).
 */
import type { AssetTemplate } from './assetTemplateTypes';

export const KIT_TEMPLATES: AssetTemplate[] = [
  {
    id: 'tenue_generate',
    name: 'Tenue Genereren',
    icon: '👕',
    category: 'tenue',
    description: 'Genereer een realistisch voetbaltenue met logo en sponsor.',
    inputRequirements: ['logo', 'sponsor', 'reference'],
    requiredAssetTypes: ['logo_upload', 'sponsor_logo_upload'],
    outputAssetType: 'kit_home',
    creditsCost: 1,
    parameters: {
      sleeves: {
        label: 'Mouwen',
        type: 'select',
        options: [
          { value: 'long', label: 'Lang' },
          { value: 'short', label: 'Kort' },
        ],
        default: 'long',
      },
      neck: {
        label: 'Hals',
        type: 'select',
        options: [
          { value: 'round', label: 'Ronde kraag' },
          { value: 'collar', label: 'Polo kraag' },
          { value: 'v_neck', label: 'V-hals' },
        ],
        default: 'round',
      },
      kit_type: {
        label: 'Type',
        type: 'select',
        options: [
          { value: 'home', label: 'Thuis' },
          { value: 'away', label: 'Uit' },
          { value: 'third', label: 'Derde' },
        ],
        default: 'home',
      },
      shirt_base: {
        visibleIf: { param: 'kit_type', excludes: ['home'] },
        label: 'Shirt Kleur',
        type: 'select',
        options: [
          { value: 'auto_home', label: 'Auto (Thuis kleuren)' },
          { value: 'auto_away_contrast', label: 'Contrast (Uit)' },
          { value: 'white', label: 'Wit' },
          { value: 'black', label: 'Zwart' },
          { value: 'red', label: 'Rood' },
          { value: 'blue', label: 'Blauw' },
          { value: 'green', label: 'Groen' },
          { value: 'yellow', label: 'Geel' },
          { value: 'orange', label: 'Oranje' },
          { value: 'purple', label: 'Paars' },
          { value: 'navy', label: 'Navy' },
          { value: 'maroon', label: 'Roodbruin' },
          { value: 'sky_blue', label: 'Lichtblauw' },
        ],
        default: 'auto_home',
      },
      pattern_style: {
        visibleIf: { param: 'kit_type', excludes: ['home'] },
        label: 'Patroon',
        type: 'select',
        options: [
          { value: 'solid', label: 'Effen' },
          { value: 'vertical_stripes', label: 'Verticale Strepen' },
          { value: 'horizontal_hoops', label: 'Horizontale Banen' },
          { value: 'diagonal_sash', label: 'Diagonale baan' },
          { value: 'half_half', label: 'Half/Half' },
          { value: 'pinstripes', label: 'Pinstripes' },
          { value: 'subtle_graphic', label: 'Subtiele Graphic' },
        ],
        default: 'solid',
      },
      shorts_style: {
        visibleIf: { param: 'kit_type', excludes: ['home'] },
        label: 'Broek Kleur',
        type: 'select',
        options: [
          { value: 'match_shirt', label: 'Gelijk aan shirt' },
          { value: 'white', label: 'Wit' },
          { value: 'black', label: 'Zwart' },
          { value: 'navy', label: 'Navy' },
          { value: 'contrast', label: 'Contrast' },
        ],
        default: 'match_shirt',
      },
      socks_style: {
        visibleIf: { param: 'kit_type', excludes: ['home'] },
        label: 'Sokken Kleur',
        type: 'select',
        options: [
          { value: 'match_shirt', label: 'Gelijk aan shirt' },
          { value: 'match_shorts', label: 'Gelijk aan broek' },
          { value: 'white', label: 'Wit' },
          { value: 'black', label: 'Zwart' },
          { value: 'contrast', label: 'Contrast' },
        ],
        default: 'match_shirt',
      },
    },
  },
  {
    id: 'legacy_tenue_generate',
    name: 'Legacy Tenue',
    icon: '🕰️',
    category: 'tenue',
    description: 'Genereer een retro/legacy tenue gebaseerd op een historisch shirt. Kies een tijdperk voor de stijl.',
    inputRequirements: ['logo', 'sponsor', 'reference'],
    requiredAssetTypes: ['logo_upload', 'sponsor_logo_upload', 'kit_legacy_upload'],
    outputAssetType: 'kit_legacy',
    creditsCost: 1,
    parameters: {
      era_style: {
        label: 'Tijdperk',
        type: 'select',
        options: [
          { value: 'default', label: 'Standaard' },
          { value: 'jaren80', label: 'Jaren \'80' },
          { value: 'jaren90', label: 'Jaren \'90' },
          { value: 'jaren00', label: 'Jaren \'00' },
        ],
        default: 'default',
      },
      sleeves: {
        label: 'Mouwen',
        type: 'select',
        options: [
          { value: 'long', label: 'Lang' },
          { value: 'short', label: 'Kort' },
        ],
        default: 'long',
      },
      neck: {
        label: 'Hals',
        type: 'select',
        options: [
          { value: 'round', label: 'Ronde kraag' },
          { value: 'collar', label: 'Polo kraag' },
          { value: 'v_neck', label: 'V-hals' },
        ],
        default: 'collar',
      },
    },
  },
  {
    id: 'keeper_tenue',
    name: 'Keeperstenue',
    icon: '🧤',
    category: 'keeper',
    description: 'Genereer een keeperstenue in contrasterende kleuren.',
    inputRequirements: ['logo', 'sponsor', 'reference'],
    requiredAssetTypes: ['logo_upload', 'sponsor_logo_upload'],
    outputAssetType: 'kit_goalkeeper',
    creditsCost: 1,
    parameters: {
      sleeves: {
        label: 'Mouwen',
        type: 'select',
        options: [
          { value: 'long', label: 'Lang' },
          { value: 'short', label: 'Kort' },
        ],
        default: 'long',
      },
      keeper_color: {
        label: 'Kleur',
        type: 'select',
        options: [
          { value: 'neon_green', label: 'Neon Groen' },
          { value: 'neon_orange', label: 'Neon Oranje' },
          { value: 'purple', label: 'Paars' },
          { value: 'neon_yellow', label: 'Neon Geel' },
          { value: 'pink', label: 'Roze' },
          { value: 'black', label: 'Zwart' },
          { value: 'red', label: 'Rood' },
          { value: 'blue', label: 'Blauw' },
          { value: 'grey', label: 'Grijs' },
        ],
        default: 'neon_green',
      },
      pattern_style: {
        label: 'Patroon',
        type: 'select',
        options: [
          { value: 'solid', label: 'Effen' },
          { value: 'graphic_print', label: 'Graphic Print' },
          { value: 'camo', label: 'Camo' },
          { value: 'geometric', label: 'Geometrisch' },
          { value: 'gradient', label: 'Gradient' },
        ],
        default: 'solid',
      },
      shorts_style: {
        label: 'Broek Kleur',
        type: 'select',
        options: [
          { value: 'match_shirt', label: 'Gelijk aan shirt' },
          { value: 'black', label: 'Zwart' },
          { value: 'contrast', label: 'Contrast' },
        ],
        default: 'match_shirt',
      },
      neck: {
        label: 'Hals',
        type: 'select',
        options: [
          { value: 'round', label: 'Ronde kraag' },
          { value: 'collar', label: 'Polo kraag' },
          { value: 'v_neck', label: 'V-hals' },
        ],
        default: 'round',
      },
    },
  },
  {
    id: 'tracksuit_generate',
    name: 'Trainingspak',
    icon: '🏃',
    category: 'tracksuit',
    description: 'Genereer een trainingspak met clublogo.',
    inputRequirements: ['logo', 'reference'],
    requiredAssetTypes: ['logo_upload'],
    outputAssetType: 'kit_training',
    creditsCost: 1,
    parameters: {
      style: {
        label: 'Stijl',
        type: 'select',
        options: [
          { value: 'modern_slim', label: 'Modern Slim' },
          { value: 'classic', label: 'Klassiek' },
          { value: 'windbreaker', label: 'Windbreaker' },
          { value: 'hoodie', label: 'Hoodie Set' },
        ],
        default: 'modern_slim',
      },
      tracksuit_color: {
        label: 'Hoofdkleur',
        type: 'select',
        options: [
          { value: 'team_primary', label: 'Teamkleur (Primair)' },
          { value: 'black', label: 'Zwart' },
          { value: 'navy', label: 'Navy' },
          { value: 'grey', label: 'Grijs' },
          { value: 'team_secondary', label: 'Teamkleur (Secundair)' },
          { value: 'red', label: 'Rood' },
          { value: 'blue', label: 'Blauw' },
        ],
        default: 'team_primary',
      },
      accent_color: {
        label: 'Accentkleur',
        type: 'select',
        options: [
          { value: 'team_secondary', label: 'Teamkleur (Secundair)' },
          { value: 'white', label: 'Wit' },
          { value: 'black', label: 'Zwart' },
          { value: 'neon', label: 'Neon' },
          { value: 'gold', label: 'Goud' },
          { value: 'silver', label: 'Zilver' },
        ],
        default: 'team_secondary',
      },
    },
  },
  {
    id: 'coach_outfit',
    name: 'Coach Outfit',
    icon: '👔',
    category: 'coach',
    description: 'Genereer een coach/trainer outfit: net pak, sweater, coltrui, polo of windbreaker.',
    inputRequirements: ['logo', 'sponsor', 'reference'],
    requiredAssetTypes: ['logo_upload', 'sponsor_logo_upload'],
    outputAssetType: 'kit_coach',
    creditsCost: 1,
    parameters: {
      outfit_style: {
        label: 'Stijl',
        type: 'select',
        options: [
          { value: 'net_pak', label: 'Net Pak (Formeel)' },
          { value: 'trainings_sweater', label: 'Trainings Sweater' },
          { value: 'coltrui', label: 'Coltrui' },
          { value: 'polo', label: 'Polo' },
          { value: 'windbreaker', label: 'Windbreaker' },
        ],
        default: 'net_pak',
      },
      outfit_color: {
        label: 'Hoofdkleur',
        type: 'select',
        options: [
          { value: 'team_primary', label: 'Teamkleur (Primair)' },
          { value: 'black', label: 'Zwart' },
          { value: 'navy', label: 'Navy' },
          { value: 'charcoal', label: 'Antraciet' },
          { value: 'grey', label: 'Grijs' },
          { value: 'team_secondary', label: 'Teamkleur (Secundair)' },
        ],
        default: 'black',
      },
      accent_color: {
        label: 'Accentkleur',
        type: 'select',
        options: [
          { value: 'team_secondary', label: 'Teamkleur (Secundair)' },
          { value: 'white', label: 'Wit' },
          { value: 'black', label: 'Zwart' },
          { value: 'gold', label: 'Goud' },
          { value: 'silver', label: 'Zilver' },
        ],
        default: 'team_secondary',
      },
    },
  },
];
