/**
 * Member templates — composite & action categories (then_vs_now, composites, walking, action).
 */
import type { AssetTemplate } from './assetTemplateTypes';

export const MEMBER_TEMPLATES_COMPOSITE_ACTION: AssetTemplate[] = [
  // ── Then vs Now Templates ──
  {
    id: 'then_vs_now_sidebyside',
    name: 'Transformation (Naast Elkaar)',
    icon: 'users',
    category: 'then_vs_now',
    description: 'Portretvideo (6 sec): legacy-versie (links) en huidige speler (rechts) naast elkaar. Ze kijken naar elkaar en lachen.',
    inputRequirements: ['person', 'reference'],
    requiredAssetTypes: [],
    outputAssetType: 'then_vs_now_sidebyside',
    creditsCost: 5,
    outputType: 'video',
    videoConfig: {
      durationSeconds: 6,
      aspectRatio: '9:16',
      resolution: '720p',
    },
    parameters: {},
  },
  {
    id: 'then_vs_now_transformation',
    name: 'Transformation (Transformatie)',
    icon: 'arrow-right-left',
    category: 'then_vs_now',
    description: 'Portretvideo (4 sec): de speler transformeert van legacy-look naar huidige look in tenue. Magisch maar realistisch.',
    inputRequirements: ['person', 'reference'],
    requiredAssetTypes: [],
    outputAssetType: 'then_vs_now_transformation',
    creditsCost: 5,
    outputType: 'video',
    videoConfig: {
      durationSeconds: 4,
      aspectRatio: '9:16',
      resolution: '720p',
    },
    parameters: {
      style_variant: {
        label: 'Transformatie Stijl',
        type: 'select' as const,
        options: [
          { value: 'hands_on_head', label: 'Handen op hoofd' },
          { value: 'spin', label: '360° Spin' },
          { value: 'clap', label: 'Klap' },
          { value: 'jersey_pull', label: 'Shirt trekken' },
          { value: 'arms_wide', label: 'Armen wijd' },
          { value: 'fist_pump', label: 'Vuist omhoog' },
          { value: 'snap', label: 'Vingerknip' },
        ],
        default: 'hands_on_head',
      },
    },
  },
  // ── Photo Composite Templates ──
  {
    id: 'photo_composite_gemini',
    name: 'Foto Composite (Beeld)',
    icon: 'camera',
    category: 'photo_composite',
    description: 'AI-composiet: legacy en huidige speler samen op een clubachtergrond. Gemini combineert beide fullbody-afbeeldingen realistisch.',
    inputRequirements: ['person', 'reference', 'background'],
    requiredAssetTypes: [],
    outputAssetType: 'photo_composite_gemini',
    creditsCost: 3,
    outputType: 'image',
    parameters: {
      background_style: {
        label: 'Achtergrond',
        type: 'select' as const,
        options: [
          { value: 'club', label: 'Clubachtergrond' },
          { value: 'stadium', label: 'Stadion' },
          { value: 'field', label: 'Speelveld' },
        ],
        default: 'club',
      },
    },
  },
  {
    id: 'photo_composite_video',
    name: 'Foto Composite (Video)',
    icon: 'clapperboard',
    category: 'photo_composite',
    description: 'MiniMax video (6 sec): de twee spelers op het composiet-beeld kijken naar elkaar, lachen, en kijken terug naar de camera.',
    inputRequirements: ['person'],
    requiredAssetTypes: [],
    outputAssetType: 'photo_composite_video',
    creditsCost: 5,
    outputType: 'video',
    videoConfig: {
      durationSeconds: 6,
      aspectRatio: '9:16',
      resolution: '720p',
    },
    parameters: {},
  },
  // ── Walking Composite Templates ──
  {
    id: 'walking_composite_far',
    name: 'Walking Composite (Ver)',
    icon: 'footprints',
    category: 'walking_composite',
    description: 'Full-body spelers ver weg op de achtergrond (15-20m afstand). Gemini plaatst beide spelers realistisch op het veld.',
    inputRequirements: ['person', 'reference', 'background'],
    requiredAssetTypes: [],
    outputAssetType: 'walking_composite_far',
    creditsCost: 3,
    outputType: 'image',
    parameters: {
      background_style: {
        label: 'Achtergrond',
        type: 'select' as const,
        options: [
          { value: 'club', label: 'Clubachtergrond' },
          { value: 'stadium', label: 'Stadion' },
          { value: 'field', label: 'Speelveld' },
        ],
        default: 'club',
      },
    },
  },
  {
    id: 'walking_composite_near',
    name: 'Walking Composite (Dichtbij)',
    icon: 'footprints',
    category: 'walking_composite',
    description: 'Full-body spelers dichtbij op de voorgrond (3-5m afstand). Gemini plaatst beide spelers groot en prominent in beeld.',
    inputRequirements: ['person', 'reference', 'background'],
    requiredAssetTypes: [],
    outputAssetType: 'walking_composite_near',
    creditsCost: 3,
    outputType: 'image',
    parameters: {
      background_style: {
        label: 'Achtergrond',
        type: 'select' as const,
        options: [
          { value: 'club', label: 'Clubachtergrond' },
          { value: 'stadium', label: 'Stadion' },
          { value: 'field', label: 'Speelveld' },
        ],
        default: 'club',
      },
    },
  },
  {
    id: 'walking_composite_video',
    name: 'Walking Composite (Video)',
    icon: 'clapperboard',
    category: 'walking_composite',
    description: 'MiniMax video (6 sec): spelers lopen van ver naar dichtbij de camera. Gebruikt het verre beeld als eerste frame en het dichtbije beeld als laatste frame.',
    inputRequirements: ['person'],
    requiredAssetTypes: [],
    outputAssetType: 'walking_composite_video',
    creditsCost: 5,
    outputType: 'video',
    videoConfig: {
      durationSeconds: 6,
      aspectRatio: '9:16',
      resolution: '720p',
    },
    parameters: {},
  },
  // ── Action Photo Templates ──
  {
    id: 'member_action_photo',
    name: 'Actiefoto',
    icon: 'zap',
    category: 'action_photo',
    description: 'Dynamische actiefoto van de speler in tenue — dribbelen, schieten, koppen en meer.',
    inputRequirements: ['person', 'reference'],
    requiredAssetTypes: [],
    outputAssetType: 'action_photo',
    creditsCost: 2,
    parameters: {
      kit_type: {
        label: 'Tenue Type',
        type: 'select',
        options: [
          { value: 'home', label: 'Thuistenue' },
          { value: 'away', label: 'Uittenue' },
          { value: 'third', label: 'Derde tenue' },
          { value: 'goalkeeper', label: 'Keeperstenue' },
        ],
        default: 'home',
      },
      style_variant: {
        label: 'Actie Stijl',
        type: 'select',
        options: [
          { value: 'dribbling', label: 'Dribbelen' },
          { value: 'shooting', label: 'Schieten' },
          { value: 'ball_at_feet', label: 'Bal aan de voet' },
          { value: 'celebrating', label: 'Vieren' },
          { value: 'heading', label: 'Koppen' },
          { value: 'sliding_tackle', label: 'Sliding' },
          { value: 'karate_kick', label: 'Karatetrap' },
        ],
        default: 'dribbling',
      },
      sleeves: {
        label: 'Mouwen',
        type: 'select',
        options: [
          { value: 'long', label: 'Lang' },
          { value: 'short', label: 'Kort' },
        ],
        default: 'long',
      },
      role: {
        label: 'Rol',
        type: 'select',
        options: [
          { value: 'player', label: 'Speler' },
          { value: 'goalkeeper', label: 'Keeper' },
        ],
        default: 'player',
      },
      shoe_color: {
        label: 'Schoenen kleur',
        type: 'select',
        options: [
          { value: 'zwart', label: 'Zwart' },
          { value: 'wit', label: 'Wit' },
          { value: 'rood', label: 'Rood' },
          { value: 'blauw', label: 'Blauw' },
          { value: 'geel', label: 'Geel' },
          { value: 'oranje', label: 'Oranje' },
        ],
        default: 'zwart',
      },
    },
  },
];
