# Generated by Django 5.1.4 on 2025-11-27 13:56

import django.db.models.deletion
from django.conf import settings
from django.contrib.postgres.indexes import GinIndex
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False  # Required for concurrent index creation

    initial = True

    dependencies = [
        ("organisations", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Event",
                "verbose_name_plural": "Audit Events",
                "db_table": "audit_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="audit_created_desc"),
                    models.Index(fields=["event_type"], name="audit_event_type"),
                    models.Index(fields=["user"], name="audit_user"),
                    models.Index(fields=["organization"], name="audit_org"),
                    models.Index(fields=["project"], name="audit_project"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=GinIndex(fields=["metadata"], name="audit_metadata_gin"),
        ),
    ]
