# Generated by Django 5.1.4 on 2025-12-04 17:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="auditevent",
            name="audit_metadata_gin",
        ),
    ]
