# Generated by Django 5.1.4 on 2026-02-04 17:46

import django.db.models.deletion
import navigation.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True, help_text="ID of the linked object", max_length=255, null=True
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display label (snapshot of object title)", max_length=255
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Frontend route (e.g., '/projects/123')",
                        max_length=500,
                        validators=[navigation.models.validate_relative_path],
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional frontend state (opaque)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the favorite was created"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Custom sort order (0 = default chronological)"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of the linked object",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this navigation item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Favorite",
                "verbose_name_plural": "User Favorites",
                "ordering": ["order", "-created_at"],
                "unique_together": {("user", "content_type", "object_id")},
            },
        ),
        migrations.CreateModel(
            name="UserRecent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True, help_text="ID of the linked object", max_length=255, null=True
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display label (snapshot of object title)", max_length=255
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Frontend route (e.g., '/projects/123')",
                        max_length=500,
                        validators=[navigation.models.validate_relative_path],
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional frontend state (opaque)"
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp of last access (auto-updates on save)"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of the linked object",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this navigation item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Recent",
                "verbose_name_plural": "User Recents",
                "ordering": ["-last_seen_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-last_seen_at"], name="navigation__user_id_af18a8_idx"
                    )
                ],
                "unique_together": {("user", "content_type", "object_id")},
            },
        ),
    ]
