# Generated by Django 5.1.4 on 2025-12-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="enable_theme_toggle",
            field=models.BooleanField(
                default=True,
                help_text="Allow users in this organisation to toggle between light and dark themes",
            ),
        ),
    ]
