# Generated by Django 5.1.4 on 2026-01-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0002_add_enable_theme_toggle"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Flexible master data storage (e.g., federation, country, league rules)",
            ),
        ),
    ]
