# Generated by Django 5.1.4 on 2026-01-30 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0003_add_metadata_fields"),
        ("sport_configuration", "0003_add_sport_hierarchy"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="sport",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary sport category for this organisation (e.g., Football, Handball)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organisations",
                to="sport_configuration.sport",
            ),
        ),
    ]
